### ISSUE TITLE
Home page stats about the platform

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#101]
Above 'Nossa stack', give a home stats with the amount of tasks, of users and bounties received using chips

![pageshot of gitpay - freelancing with git 2018-07-01-1559 26](https://user-images.githubusercontent.com/88840/42455868-aea8476a-8393-11e8-922c-d279b875b4c4.png)

### Why
The community should be able to track how many users, task and bounties and being created on the platform

### Level
Medium

### Useful links

- We use chips component: https://material-ui.com/demos/chips/
- The home component: https://github.com/worknenjoy/gitpay/blob/master/frontend/src/components/welcome/welcome.js

### Screenshot attached
![screen shot 2018-07-09 at 4 20 38 pm](https://user-images.githubusercontent.com/88840/42456026-17da391e-8394-11e8-8f61-ab0a87731c2d.png)

A chip component. We should create a similar with a related icon

### How to solve this issue

- Create a new route (for example: `/info` or `/data`)
- The data should retrieve:
```
{
tasks: [total of tasks],
orders: [total of value from tasks],
users: [total of users]
}
```
- Connect the Welcome component to redux
- Create actions to retrieve the data
- Create the chips components with the data retrieved

### What you will need to complete this issue
You don't need any extra api key to solve this issue

**Comment by lucianojfj** [comment]
@alexanmtz please close this issue.

**Comment by alexanmtz** [comment]
Closing this and released 🚀 , thanks @lucianojfj
