### ISSUE TITLE
Add a comment on github when issue is added to gitpay

### ISSUE THREAD

**Issue by thdelmas** [worknenjoy/gitpay#1012]
Description 

When someone add an issue to gitpay
We could have an automation to comment on the github issue with the link to gitpay

### Why
This will lead people to know about gitpay
It will motivate people to solve the issue
As an automation, the repo owner won't have to it manually

### Level
Level required to conclude this issue
- Intermediate

### Current behavior
Currently there's no such automation

### Expected behavior
1. A new issue is added on gitpay
2. A bot will receive a hook with issue details
3. The bot will comment on github providing the gitpay link to the issue
4. (Could also provide more info about the bounty)

### Useful links
- Use case example: https://github.com/horizonxyz/horizon/issues/29

### What you will need to complete this issue
- Some kinds of hooks
- A bot that connect to github or other git

**Comment by alexanmtz** [comment]
@thdelmas this suppose to work, we have a Gitpay bot to update issues but it stopped to work again, we need to check.

If you look on our code, we have the bot module:
https://github.com/worknenjoy/gitpay/tree/master/modules/bot

**Comment by alexanmtz** [comment]
We already implemented but for some reasons comments are not showing, we will have this implemented when we have our Github Action, so lets close for now
