### ISSUE TITLE
Allow user to sort issue

### ISSUE THREAD

**Issue by thdelmas** [worknenjoy/gitpay#1013]
Sort issues on the issues explorer table.

**Comment by Precious-Macaulay** [comment]
Please assign this issue to me

**Comment by oleksandr-shvets** [comment]
@Precious-Macaulay How it's going? May I help you? 
I can add sort param to the backend, or create UI front-end for this feature.

**Comment by Precious-Macaulay** [comment]
Please i need the ui frontend for the feature

**Comment by oleksandr-shvets** [comment]
> Yes Please i need the ui frontend for the feature
Okay. I will try do this till the end of the week.

**Comment by alexanmtz** [comment]
@oleksandr-shvets for now the sort will be front-end only, no need to add to the server some filtering for this version, as we have the pagination on the front-end.

**Comment by Precious-Macaulay** [comment]
> .

Don't worry about the ui design i will work with mui and implement the feature from the frontend.

**Comment by oleksandr-shvets** [comment]
> @Precious-Macaulay
> Don't worry about the ui design i will work with mui and implement the feature from the frontend.

It's not necessary. MUI already have UI for table sorting.  See example — [Sorted table demo](https://mui.com/material-ui/react-table/#tableTitle)
I will use `<TableSortLabel>` component.

**Comment by Precious-Macaulay** [comment]
>It's not necessary. MUI already have UI for table sorting. See example — [Sorted table demo](https://mui.com/material-ui/react->table/#tableTitle)
>I will use <TableSortLabel> component.

exactly, i will use that to add the feature thanks.

**Comment by oleksandr-shvets** [comment]
@Precious-Macaulay  @alexanmtz 
Done. Here is a PR: https://github.com/worknenjoy/gitpay/pull/1068/files

**Comment by Precious-Macaulay** [comment]
@alexanmtz the issue has been fixed. review #1074

**Comment by Precious-Macaulay** [comment]
@alexanmtz please review #1075
