### ISSUE TITLE
Fix Lint issues

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#1038]
When you do a push you will see many lint errors, and we need all those fixes so we can have the push hook green

**Comment by alexanmtz** [comment]
@KenjxJJ can you work on this?

**Comment by KenjxJJ** [comment]
Yes.

**Comment by effaf** [comment]
Hi @alexanmtz , I would like to work on this if there is no resolution yet.

**Comment by alexanmtz** [comment]
Hello @effaf , there's no resolution yet; feel free to work on it.

**Comment by effaf** [comment]
Hi @alexanmtz , thank you for assigning the issue. I have a few questions before I get started on this. 
1) I ran the command ```npx eslint --fix . ```, and could see 104 errors. A lot of these errors were parsing errors due to older eslint version. Can I change the ecmaVersion in the configuration file? 
2) Do you want me to comment out the ```console.log ``` or delete it? 
3) A lot of libraries have been imported but not used. Would the maintainers prefer deleting the code or commenting it out?

**Comment by alexanmtz** [comment]
> Hi @alexanmtz , thank you for assigning the issue. I have a few questions before I get started on this.
> 
> 1. I ran the command `npx eslint --fix . `, and could see 104 errors. A lot of these errors were parsing errors due to older eslint version. Can I change the ecmaVersion in the configuration file?
> 2. Do you want me to comment out the `console.log ` or delete it?
> 3. A lot of libraries have been imported but not used. Would the maintainers prefer deleting the code or commenting it out?

Hey, @effaf, thanks for jumping into this issue and your proactivity. You can change the ecmaVersion in the configuration, and we can eliminate all `console.logs` except the one with the comment `// eslint-disable-next-line no-console`

And we can remove the unused libraries.

**Comment by alexanmtz** [comment]
Hey @effaf, some progress on this one?

**Comment by alexanmtz** [comment]
There's a bounty of $20 for this one: https://gitpay.me/#/task/840

**Comment by guvitorino** [comment]
> There's a bounty of $20 for this one: https://gitpay.me/#/task/840

I started working on this issue. I saw the comments above and will take them into consideration

**Comment by alexanmtz** [comment]
That's great @guvitorino, looking forward to review your solution and feel free to change the configuration as suggested before

and fix automatically some issues with `npm run lint-fix`

**Comment by Anshgrover23** [comment]
hi i am also doing this

**Comment by Anshgrover23** [comment]
/attempted Fix Lint issues #1038, plss check @alexanmtz also there is some parsing error were not resolving can u plss check

**Comment by alexanmtz** [comment]
Hello @Anshgrover23 , thanks for sending the PR, I will review in the weekend and when it's merged you can claim the bounty on the web page by going in "Solve issue" and pasting your PR when is merged in "Send Solution" tab

**Comment by alexanmtz** [comment]
Hey @guvitorino, we have already a PR to review for this one, so let's find another issue for you :)

**Comment by Anshgrover23** [comment]
@alexanmtz thanks buddy, waiting for your merge reply and thanks for giving me chance

**Comment by Anshgrover23** [comment]
@alexanmtz made some more commit changes review the pr once again please sir.

**Comment by Anshgrover23** [comment]
@alexanmtz solved the optonal chaining errors . check new commit

**Comment by alexanmtz** [comment]
Hey @raviteja83, you fixed this issue successfully; many thanks for the contribution 🚀

You can claim your bounty by visiting this issue on Gitpay: https://gitpay.me/#/profile/task/840/fix-lint-issues

On "Solve Issue" and on the "Send Solution" tab, you can paste the PR merged and the Bounty process will be initiated I hope :)

**Comment by raviteja83** [comment]
@alexanmtz I did do the above. where do I check if the bounty process in initiated? payments page seems to have a bug
<img width="1256" alt="image" src="https://github.com/worknenjoy/gitpay/assets/6763261/42f48b87-91cf-4c3f-9560-60de54894223">
