### ISSUE TITLE
Some messages to author are not sending

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#1056]
We have the following error when we try to send invites to some authors on the Issue page

This case for example: https://gitpay.me/#/task/739/allow-user-to-sort-issue

It works, but we have some situations that we have the following error:

```
not possible send invite
Error: Request failed with status code 403
errorError: Request failed with status code 403
error
Error: Request failed with status code 403
```

You need to investigate locally, adding issues and trying to reproduce the use case and see why some users can send the e-mails.

### Good to know
- Our e-mail system outputs on the server log the email content when we send locally.

**Comment by saram-aman** [comment]
@alexanmtz taking the issue, will come-up with the solution, thank you!

**Comment by alexanmtz** [comment]
Hey @saram-aman , are you still up for solving this? You can have the branch with the issue number, something like:
`fix/1056-message-to-author-not-working`

**Comment by alexanmtz** [comment]
Fixed 💯
