### ISSUE TITLE
Cannot import issue "Error to update issue"

### ISSUE THREAD

**Issue by Zahrun** [worknenjoy/gitpay#1083]
Hi there,

I want to fund some issues: https://github.com/mono/mono/issues/14412 and https://github.com/keepassxreboot/keepassxc/issues/2281.

When I click on "import issue" and input any of these two issues url, it shows "Error to update issue".

**Comment by Zahrun** [comment]
https://github.com/worknenjoy/gitpay/issues/1083 also fails

**Comment by alexanmtz** [comment]
@Zahrun, we have solved it for now; some of the issues already exist, and we have better feedback now. I think there's a case when the Github API limit is exceeded, and now we have a specific notification for it. We will work to better handle Github API calls or even not depend on them if they're not available in the near future.

Can you test again?

![FireShot Capture 001 - Gitpay - Bounties for git issues solved - gitpay me](https://github.com/worknenjoy/gitpay/assets/88840/ea922299-ae68-4d4c-9fee-a5adbdc424f9)

**Comment by Zahrun** [comment]
I found under my profile the 3 issues were already created. I deleted the one related to https://github.com/worknenjoy/gitpay/issues/1083 and then created it again. Tried that on mobile the other day and it failed with "actions.task.issues.error.notfound". Maybe deleting and recreating is not supported. Now from laptop I tried again and got "Error to update issue" then refreshed the my profile and it was in the list, created "a few seconds ago".
I cleared cookies and site data, reloaded the page, added a different issue `https://github.com/pacstall/chaotic-PPR/issues/5`, and got again "Error to update issue". Refreshed the profile, and the issue is listed there as actually created.

**Comment by alexanmtz** [comment]
> I found under my profile the 3 issues were already created. I deleted the one related to #1083 and then created it again. Tried that on mobile the other day and it failed with "actions.task.issues.error.notfound". Maybe deleting and recreating is not supported. Now from laptop I tried again and got "Error to update issue" then refreshed the my profile and it was in the list, created "a few seconds ago". I cleared cookies and site data, reloaded the page, added a different issue `https://github.com/pacstall/chaotic-PPR/issues/5`, and got again "Error to update issue". Refreshed the profile, and the issue is listed there as actually created.

Thanks for reporting, @Zahru, I will work to fix those bugs.

**Comment by Zahrun** [comment]
Issue created successfully on Gitpay
This issue was imported already

It seems to work, very nice, thank you
