### ISSUE TITLE
Cannot fetch pull request data

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#1085]
```
TypeError: Cannot read properties of null (reading 'dataValues')
    at /app/modules/tasks/taskSolutionFetchData.js:54:54
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
taskSolutionFetchData error on controller Error: COULD_NOT_FETCH_PULL_REQUEST_DATA
    at /app/modules/tasks/taskSolutionFetchData.js:85:11
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:473:21)
```

**Comment by Dheeraj4103** [comment]
Hey @alexanmtz can work on this issue.

**Comment by alexanmtz** [comment]
Hey, @Dheeraj4103, yeah, feel free to get into this. it may be challenging to reproduce, but you can import an issue locally, go to the "Solve issue" and "Send Solution" tabs, paste one associated PR, and send a solution. You probably can't send the solution because you must be logged in with Github, but let me know if the error happens when fetching the data.

**Comment by Dheeraj4103** [comment]
Ok, understood.
Thanks for helping

**Comment by Dheeraj4103** [comment]
While recreating this issue i got this response.
![image](https://github.com/user-attachments/assets/2893838b-7707-4b85-9414-fd57be71e62a)

**Comment by alexanmtz** [comment]
Hey @Dheeraj4103 , you're having this response because you're not authenticated. Once you authenticate locally, you can copy the token from the request and pass to Postman as an authorization bearer token, and you can evaluate better.

But checking the line which is causing the error
https://github.com/worknenjoy/gitpay/blob/66a0473ca7560b99099aa7a898e134d9175e3bc8/modules/tasks/taskSolutionFetchData.js#L55C7-L55C9

You will see that maybe the assignment is null, and we need to handle that. I will do some tests here to investigate the best solution, but I think the verification for the issue close should not have this assignment verification. However, a current solution to avoid the error is to check the property conditionally.

**Comment by Dheeraj4103** [comment]
Ok, I will work on it

> Hey @Dheeraj4103 , you're having this response because you're not authenticated. Once you authenticate locally, you can copy the token from the request and pass to Postman as an authorization bearer token, and you can evaluate better.
> 
> But checking the line which is causing the error https://github.com/worknenjoy/gitpay/blob/66a0473ca7560b99099aa7a898e134d9175e3bc8/modules/tasks/taskSolutionFetchData.js#L55C7-L55C9
> 
> You will see that maybe the assignment is null, and we need to handle that. I will do some tests here to investigate the best solution, but I think the verification for the issue close should not have this assignment verification. However, a current solution to avoid the error is to check the property conditionally.

**Comment by Dheeraj4103** [comment]
Hey @alexanmtz,
Can you help me to recreate this issue, maybe we could take a google meet, If that is okay with you ?

**Comment by alexanmtz** [comment]
Hey @Dheeraj4103 let me go throught it to reproduce and I will get back to you soon

**Comment by Sajid-tech** [comment]
@alexanmtz If the issue is still open , I would like to contribute, ASSIGN me

**Comment by alexanmtz** [comment]
Hey @Dheeraj4103 and @Sajid-tech, there's an issue on this flow that I have to work properly on it; please feel free to comment on any other issue you're interested in solving :)
