### ISSUE TITLE
Cannot make a payment on an issue

### ISSUE THREAD

**Issue by dextertd** [worknenjoy/gitpay#1103]
(Writing this here as I couldn't see a support link on the site.)

Have tried from two different devices to pay with a credit card but after entering card details and hitting the Pay button I see 

> There was an error to update this issue

![screenie](https://github.com/worknenjoy/gitpay/assets/54495183/5cf2cb61-a4e6-4779-aee9-a7b5e5e608b1)

Reset browser cache and tried on a different device (mac and linux) to no avail.

**Comment by alexanmtz** [comment]
Hello @dextertd , thanks for reporting this.

I've been looking through the logs, and it seems an issue with the GitHub API call rate limit. I pushed a fix to inform the user in that case, and we're looking for a solution to not depend on the GitHub API calls for these cases.

But I hope it is fixed now. Let me know if you have any issues.

**Comment by dextertd** [comment]
Hi @alexanmtz I just tried again and saw the same behaviour. Pleased to hear it's being looked into regardless. Thank you.

**Comment by alexanmtz** [comment]
Hello @dextertd, thanks for the feedback. It's sad to hear that you're having the same issue again. I will try to investigate the cause in this case because all other payments seem to be working. I tried to pay recently for a Gitpay issue, and it's working. Are you trying to use a credit card number or PayPal? And if you try again, please let me know the date and time, and it would be great to

**Comment by dextertd** [comment]
Hi @alexanmtz just tested now, 2024-06-17 18:41 UTC, credit card.

**Comment by alexanmtz** [comment]
Hey @dextertd , I am still figuring out your issue; I can see it is returning 400 from the server, and now I added some logging to have a better overview. Can you try to make a new payment again?

**Comment by dextertd** [comment]
@alexanmtz Just done another in the same way on that issue, 19:44 UTC, credit card.

**Comment by alexanmtz** [comment]
Hey @dextertd, thanks for taking your time again and helping me get through this issue, and sorry for the inconvenience. We found an issue with payments for nonregistered users, and we fixed it yesterday. Everything should be good now.

You can create an account on Gitpay to make a payment, or you can proceed as you were doing by making a payment without creating an account.

**Comment by dextertd** [comment]
Thanks for all the hard work @alexanmtz. Was able to make a payment.
