### ISSUE TITLE
Add the related icon for the Skills page

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#1120]
Add in this page a proper icon for each language following the same style.

Here is source you can use:
- https://devicon.dev/
- https://github.com/bablubambal/All_logo_and_pictures
- https://www.flaticon.com/free-icons/programming-language

Add to our skills page

![pageshot of 'Gitpay - Bounties for git issues solved' @ 2024-08-23-1427'15](https://github.com/user-attachments/assets/64795457-5b8e-41e5-9f63-6c0ce9bee312)

**Comment by alexanmtz** [comment]
Amazing 🥇 @nvlled , thanks for the contribution

One question, where you got the icons from? I need to put an appropriate credit to the source

**Comment by nvlled** [comment]
Oh yeah, I forgot about that. I got almost everything from https://devicon.dev, except those listed below.

These icons are downloaded from flaticon:

- _Writing.svg_ created by nawicon 
- _Blogging.svg_ created by Fathema Khanom 
- _Testing.svg_ created by juicy_fish 
- _Continuous Integration.svg_ created by Arkinasi
