### ISSUE TITLE
Unable to activate my bank account

### ISSUE THREAD

**Issue by LevisNgigi** [worknenjoy/gitpay#1148]
I am a new gitpay user and everytime I try adding a bank account/activating my bank account I get the prompt that says "we could not create your account".

**Comment by alexanmtz** [comment]
Hey @LevisNgigi, thanks for reporting this. I've been looking at the logs, and it's not recognizing your routing number as valid. Can you try to enable the option "Provide IBAN instead" and provide the IBAN of your account?

**Comment by LevisNgigi** [comment]
I do not have an IBAN as In Kenya, banks use a SWIFT/BIC (Bank Identifier Code) and your local bank account number for international transactions instead of an IBAN.

**Comment by alexanmtz** [comment]
Hey @LevisNgigi, I see; thanks for clarifying; I will check in your case how to proceed with the bank account registration.

**Comment by LevisNgigi** [comment]
Thank you @alexanmtz . I do no know if wise can be an option?

**Comment by alexanmtz** [comment]
> Thank you @alexanmtz . I do not know if wise can be an option.

It's not the best option. Having your local bank account is always better, and we are improving the support for accounts like Wise and Revolut.

I will look into your case and get back to you with an update so you can proceed and test with your local account 🙏

**Comment by LevisNgigi** [comment]
> > Thank you @alexanmtz . I do not know if wise can be an option.
> 
> It's not the best option. Having your local bank account is always better, and we are improving the support for accounts like Wise and Revolut.
> 
> I will look into your case and get back to you with an update so you can proceed and test with your local account 🙏

Sounds fine.Thank you for taking your time on this.

**Comment by alexanmtz** [comment]
@LevisNgigi I contacted you by e-mail to provide you the proper support and complete your bank account registration 🙌

**Comment by LevisNgigi** [comment]
> @LevisNgigi I contacted you by e-mail to provide you the proper support and complete your bank account registration 🙌

Thank you, I have replied. I appreciate it.
