### ISSUE TITLE
Favicon for GitPay

### ISSUE THREAD

**Issue by mthais** [worknenjoy/gitpay#12]
define a favicon to the platform [Gitpay](gitpay.me)

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/64

**Comment by gellys** [comment]
Hello everyone. Add me, please?

**Comment by alexanmtz** [comment]
This is the favicon that should be added
![9gCANvoJ](https://user-images.githubusercontent.com/88840/58431414-f0d99680-80ad-11e9-8a54-3d1c0a96ee0b.png)

**Comment by alexanmtz** [comment]
Merged, deployed 🚀  and bounty sent 💸 , thanks @lorenzdesmedt to contribute!

**Comment by lorenzdesmedt** [comment]
Thanks Alexandre, received the bounty!

Op vr 31 mei 2019 om 01:18 schreef Alexandre Magno <notifications@github.com
