### ISSUE TITLE
Remove errors from ESLint

### ISSUE THREAD

**Issue by wharley** [worknenjoy/gitpay#123]
It's necessary remove all errors what the ESLint show when is run command of verify Javascript pattern what was configurated on project.

### Why
To maintain a standard of code

### Level
Medium

### Expected behavior
Today is configured not to pass eslint error in prepush. You need to run git push with success

### How to solve this issue
All message what ESLint show are intuitive

### What you will need to complete this issue
You need to run git push with success

### Tips
It is exist plugins to ide vscode and atom to help on solution.
- Prettier plugin

**Comment by alexanmtz** [comment]
Merged 🚀
