### ISSUE TITLE
Date to delivery

### ISSUE THREAD

**Issue by wharley** [worknenjoy/gitpay#136]
When I choose a date, an earlier date is set.

### Why
Because it is set to date incorrect

### Level
Medium

### Current behavior
Setting incorrect date

### Expected behavior
Set date correct

### How to reproduze the user scenario

![screencast 2018-08-06 at 11 36 54 pm](https://user-images.githubusercontent.com/11954498/43752783-fe624750-99d8-11e8-8c1c-74b403b8d64f.gif)

**Comment by alexanmtz** [comment]
Merged 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 , thanks @raivitor
