### ISSUE TITLE
Save Card number of customer for use in other task payment 

### ISSUE THREAD

**Issue by mthais** [worknenjoy/gitpay#167]
### Description 
To improve the payment process on gitpay, the system could store the card number of the user that was used to paid the last issue.

### Why
Every time that the user needs to pay an issue, the system solicits to the user the card number again, the user loses much time doing this process.

### Level
Medium

### Current behavior
* The user makes a payment for an issue on gitpay and the system don't store their card number for to use in another task payment .

### Expected behavior
 * The system will show the field "Número do cartão", just when the user to click on the link "Adicionar método de pagamento".  
* When the user inserts their card number on gitpay and selects the option "Salvar os dados deste cartão", the system will store this information.
* The system will show the card number information that was stored.

#### Actually Payment option screen 

![modulo de pagamento](https://user-images.githubusercontent.com/27444220/47806098-ab233e00-dd17-11e8-8b0f-fd97af3127e7.png)

#### Expected Payment option screen 

![modulo de pagamento_storecardnumber](https://user-images.githubusercontent.com/27444220/47806148-cd1cc080-dd17-11e8-8c91-26e9a0f52219.png)

### How to solve this issue
It's necessary to create a check button "Salvar os dados deste cartão" to store the information about users card numbers when was checked and show this card number on the screen to user choose what is the card want to use to make payment.

### How to reproduce the user scenario

 - Access a task on gitpay;
 - Choose the option " Adicionar recompensa";
 - Insert any value;
 - The system show a poup-up with payment options;

### What you will need to complete this issue
* You will need the Stripe development keys that will be send to you after this task is assigned to you.

**Comment by alexanmtz** [comment]
Let's close this for now to create a area to setup cards
