### ISSUE TITLE
The task isn't change on gitpay when the user change these on github

### ISSUE THREAD

**Issue by mthais** [worknenjoy/gitpay#169]
### Description 
When the user changes the issue on Github that was registered on gitpay, the gitpay system doesn't refresh this task.

### Why
We have a problem because we don't have the same information in these two places.

### Level
Beginning

### Current behavior
* The user registers an issue on GitHub and inserts this task on Gitpay, so the user needs to change some wrong information and change this information on GitHub but the gitpay application won't refresh this information.

### Expected behavior
* It's necessary to synchronize this information when the user changes some information on github,  the gitpay should also automatically change it too.

### How to solve this issue

* Create a routine to synchronize the two systems

### How to reproduce the user scenario

 - Insert an available issue like a task on gitpay;
 - Change some information in the same issue on gitHub;
 - The gitpay system won't change this information automatically;

**Comment by alexanmtz** [comment]
@mthais this is still an issue?

**Comment by mthais** [comment]
@alexanmtz Just the task title that isn't working ok.

**Comment by alexanmtz** [comment]
So I will close this for now
