### ISSUE TITLE
Delete a task created on gitpay

### ISSUE THREAD

**Issue by mthais** [worknenjoy/gitpay#170]
Description 

When the user creates a task on gitpay, the system doesn't have a functionality for the user to delete this task.

### Why

It's necessary to create a function that allows the user to delete a task that the user created wrong or gave up

### Level
Beginning 

### Current behavior

* The user inserts a task and when the user needs to delete this task, the system doesn't have this functionality.

### Expected behavior
* The user inserts a task and when the user needs to delete this task, the system will have a button "Excluir " that when clicked, the system shows the message "Deseja excluir esta tarefa?" in a poup-up.

#### Option- delete on task screen

![pageshot of gitpay - freelancing with git 2018-10-31-1439 36](https://user-images.githubusercontent.com/27444220/47811409-7a95d100-dd24-11e8-94c6-2c0a5941f0fa.png)

### How to solve this issue

 * Insert a button on the task screen called "Excluir";
 * Implement a functionality to delete this task on the database;

### How to reproduce the user scenario

 - Access the task screen;
 - The system shows the options for the user about the task;
 - The system shows a button "Excluir" for the user;

### Tips
- We already have the action to delete, and now we need the implementation on the front-end

**Comment by alexanmtz** [comment]
Great @rafael-acerqueira 🎉 

No problem about your starter experience, It's for learning purpose indeed.
I sent an invite, when you accept I will assign for you.

The backend is already implemented, so it's a good task to learn react and redux by doing

**Comment by rafael-acerqueira** [comment]
Awesome @alexanmtz 

I'm going to start tonight. I let you know if a have any doubts, ok ?

**Comment by alexanmtz** [comment]
Great @rafael-acerqueira 👍

**Comment by rafael-acerqueira** [comment]
Can I change the delete icon? At the screenshot is showed delete_outline icon, but in the frontend dependencies I don't have this icon.
![delete-icons](https://user-images.githubusercontent.com/9022148/52021792-1e824a80-24d5-11e9-8639-1c41f726fe1b.png).

Can I use delete instead of delete_outline?  ![delete-icons-site](https://user-images.githubusercontent.com/9022148/52021834-483b7180-24d5-11e9-9801-1b78341e59ba.png)


I have found this icon at material-ui/icons version 3.2, but our version is "^1.0.0-beta.34" and we don't have icons folder.
![delete outline](https://user-images.githubusercontent.com/9022148/52022096-268eba00-24d6-11e9-883a-ffafcaaf171d.png)

What do you think about it ?

**Comment by alexanmtz** [comment]
Hello @rafael-acerqueira, good observation, we need to update our Material ui version indeed.

You can use icons from the icon library from material ui, that's how they did in old versions, so for the add icon, for example: `import AddIcon from material-ui-icons/Add`

So you can use the delete from here: https://material.io/tools/icons/?style=baseline

And I think will work with `import DeleteIcon from material-ui-icons/Delete`

**Comment by alexanmtz** [comment]
And something which is not described on the issue but will be necessary, it's when the user click on delete, it opens a popup (dialog) to confirm, otherwise the user can delete by accident and if there's bounty added, it will be lost, so good to have a confirmation in this case.

If you think this solution will increase the complexity for you, you can use a default javascript confirm, but if you decide to proceed there's good example in the task component of how to open a dialog.

**Comment by rafael-acerqueira** [comment]
> Sorry for the confusion @rafael-acerqueira, yeah, you can use the delete icon for now.

No problem, I didn't explain very well

**Comment by alexanmtz** [comment]
great @rafael-acerqueira and sorry about the task component, we will need a huge refactoring to split it in more components to be more readable and maintainable.

**Comment by rafael-acerqueira** [comment]
It's no problem. Our code always can be improved

**Comment by rafael-acerqueira** [comment]
@alexanmtz, I believe that I have finished this task. How can I proceed? Do I create a branch and commit there and then I create a PR ?

**Comment by alexanmtz** [comment]
Great @rafael-acerqueira , you should have created a fork, and push to a branch and make a PR from your branch. If you created your branch from our repo, you should add a new remote with your fork.

There's a great tutorial about the fork workflow: https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow

If this is the case, to not loose what you did, you can proceed adding a new remote with your fork from the repo that you already did the changes.

1. Create your fork here in Github from the main repo in "fork repo"
2. You should do the following in your command line from the project root: `git remote add rafael url-of-your-fork` and then push your branch to this new remote: `git push rafael your-branch-name`

I recommend not use master and create a branch for each change you make.

I hope it helps and if you need something just let me know.

**Comment by alexanmtz** [comment]
Oh, great that you created the forked already @rafael-acerqueira.

So you should commit (pay attention if your commit have only the files you changed for this PR), push to a branch in your forked repo (it can be the same name) exactly as you mentioned.

From that, you will have a remote branch in your forked repo. To create a PR, if you go the Github repo page, it will show a notification about your new branch, asking if you wanna create a PR from that, so you have to follow the instructions from there and then the PR will be created.

**Comment by rafael-acerqueira** [comment]
I got it! https://github.com/worknenjoy/gitpay/pull/319

**Comment by alexanmtz** [comment]
Great @rafael-acerqueira , I reviewed, please take a look on the comments and suggestion, I will deploy a test app as well to see the result before we merge.

**Comment by rafael-acerqueira** [comment]
@alexanmtz, as soon as possible I will take a look on the comments and I will make the changes

**Comment by alexanmtz** [comment]
Deployed to production and excellent first contribution @rafael-acerqueira 🚀 🥇
