### ISSUE TITLE
New purchase on the card with wrong language

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#173]
The following template e-mail are being send in English when the language from the source is set in Brazilian Portuguese

```
This email is to inform you that a payment was made in your credit card for a task on Gitpay. When the task been concluded, the payment will be sent for who you assigned.

Name on credit card: Foo

Last 4 digits: 222

Thanks, 
Gitpay Team

----------------------
https://gitpay.me (Web) 
tarefas@gitpay.me (Email) 
Worknenjoy Inc., 2035 Sunset Lake Road #Suite B-2, Newark, DE 19702 (Mail) 

```

### Why
The user should receive the email in the language he set, the default is in English but in this case, he is receiving the email in English even if the preferences are set as default language Brazilian Portuguese

### Level
Beginner

### Current behavior
An email when a payment for a task is made is sending always in English

### Expected behavior
The user should receive the e-mail in the language they set

### How to solve this issue
Find in the node part the mail folder with all the e-mail templates, and there are payment emails templates that should be investigated about why the text is always set for English language

### How to reproduce the user scenario

 - Run the project locally following the documentation
 - Create your account
 - Create an issue on the main screen for any issues from Github
 - Setup your language preference to Portuguese
 - Create a test payment with card number: *4242424242424242*
 - You will receive an email confirming the payment purchase (in English)

### What you will need to complete this issue
- You need the stripe test API keys that we provide

**Comment by renatoramiro** [comment]
I would like to contribute with this issue.

**Comment by alexanmtz** [comment]
Great @renatoramiro , you were assigned! Please start to run the project locally in order to start to work on the issue

**Comment by saikiranmarripati** [comment]
I would like to contribute with this issue.

**Comment by alexanmtz** [comment]
@saikiranmarripati great, I assigned you and you can start to work on it. Please start to run the project locally in order to start to work on the issue. 

Please [join our slack channel](https://join.slack.com/t/gitpay/shared_invite/enQtNDg4NzM2NDI5NDg4LTk1ZTlhMGJhOGJlOGJhNjgzNTJjM2QxMmNjM2M4Njk0YjllZDBiZDFjZTVlMzBiMzU0NTI3NjE2YWNhNjllOTQ) in order to get support:

I will send you the development keys for you, so you will be able to test the payment for a bounty locally to reproduce the bug and be able to fix it.

**Comment by alexanmtz** [comment]
@saikiranmarripati it's been a while without any updates from this, so I will remove you from this issue

**Comment by nobady90** [comment]
Hi, if you want, from next week, I can watch it.

**Comment by alexanmtz** [comment]
Amazing @nobady90 , I will assign you and then you can start

**Comment by alexanmtz** [comment]
Merged and deployed, thanks @nobady90 for your great contribution 🚀
