### ISSUE TITLE
Create a slack icon for our channel

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#184]
We need a slack button on the top bar, once you click, a dialog appear you can add an email to receive an invite. But for this will add the e-mails for an mailchimp list. We already use Mailchimp on the main form, so you will use something similar.

The slack integration requires the Slack API, but we will add on a Mailchimp list that will send for Slack later.

The slack button attached should be placed on the top right
![screen shot 2018-11-19 at 6 38 39 pm](https://user-images.githubusercontent.com/88840/48725219-c8b73980-ec2b-11e8-91b0-2812e26690c6.png)

### Screenshot attached
![screen_shot_2018-10-04_at_9 06 54_pm](https://user-images.githubusercontent.com/88840/48727009-4fbae080-ec31-11e8-9f70-ed99fba8d7e7.png)

### Level
Medium

### What you will need to complete this issue
You don't need anything extra to complete the issue, just follow the project documentation, and any information about the Mailchimp list should be leaved as placeholder.

### Tips
See the existing integration about Mailchimp that is already working on the project in the component `welcome.js`

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Slack channel](https://trello.com/c/ke0IQ8cy/221-slack-channel)

**Comment by riddokun** [comment]
codemill$10

**Comment by riddokun** [comment]
I can't do any npm commands on this project. I have to resign the offer :(

**Comment by alexanmtz** [comment]
@farolanf you mean on the front-end? And for this offer you can implement using directly the slack API and count users as the example? 

Can you open an issue describing this issue with modules so we can address in other PR?

**Comment by farolanf** [comment]
@alexanmtz yes, on the front-end. OK, I'll use the Slack API instead of adding to mailchimp list.

> Can you open an issue describing this issue with modules so we can address in other PR?

Will do that now.
