### ISSUE TITLE
Fix Responsive topbar

### ISSUE THREAD

**Issue by mthais** [worknenjoy/gitpay#191]
In version mobile, the gitpay website is showing some layout error. Check it on image bellow.

### Why
The gitpay platform should work in all devices including mobile.

### Level
Medium

### Current behavior
When the user accesses the Gitpay website by mobile, the website is showing the screen not responsive.

### Expected behavior
When the user accesses the Gitpay by mobile, the website should to showing the screen with all layout responsive, to work in all dispositive.

### Screenshot attached
![whatsapp image 2018-11-27 at 21 29 48](https://user-images.githubusercontent.com/27444220/49251486-99ad7e80-f408-11e8-812d-f90515117ce7.jpeg)

### How to solve this issue

- You need to implement a responsive feature;

### How to reproduce the user scenario

-  Run the project locally;
-  Access the website of Gitpay by mobile;
-  On top of website, the icons don't work correctly;

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/109
