### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ease' of undefined

### ISSUE THREAD

**Issue by mathvaleriano** [worknenjoy/gitpay#193]
### Description 
This bug occurs when i click at the chevron right button while i'm using mobile version.

https://gitpay.me/#/task/109

### Screenshot attached
![bug](https://user-images.githubusercontent.com/12265496/49401211-a9410600-f72d-11e8-998f-dccd407d2ca8.png)

### How to reproduze the user scenario
- change to mobile
- click at the chevron right button

**Comment by alexanmtz** [comment]
thanks for report @mathvaleriano , it's seems the animation library is missing

**Comment by alexanmtz** [comment]
I think is fixed now
