### ISSUE TITLE
Go to account button

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#20]
![screen shot 2018-06-04 at 2 01 35 am](https://user-images.githubusercontent.com/88840/40892774-414d3de2-679b-11e8-872c-03be00efbac9.png)

When logged, this blue button should change the label and the action direct user to account

## How to fix

There's a logic that changes the button to hidden if is logged, you should make this button appear with a diferent label, and a different `onClick` handler

**Comment by WalshJP** [comment]
codemill$20

**Comment by alexanmtz** [comment]
Are you working on this @WalshJP ?
