### ISSUE TITLE
Send an invite to fund an issue

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#222]
Invite a user to add funds to an issue added on Gitpay.

We have already an invite to contributors that were done in #129 and a new design for that page.

You will need to use the same component, so we need to refactor the code to invite contributors in order to reuse one same component for both.

An email should be sent to the address provided in the following format:

```
Hello,

{username} invite you to contribute with ${value} for the issue ${title}.

He suggested the deadline for ${date}

{message}

You can add a bounty at {url}.

```

### Level
Medium

### Screenshot

![Desktop](https://user-images.githubusercontent.com/88840/74260537-f4738300-4cf9-11ea-9e13-4e0fd4520b10.png)

![Desktop Copy](https://user-images.githubusercontent.com/88840/74260531-f0dffc00-4cf9-11ea-969a-d6ffbab9067a.png)

### Assets
![fund-invite](https://user-images.githubusercontent.com/88840/74332641-774a1b80-4d96-11ea-892a-b3ff043ebf46.png)

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Send invite to fund an issue](https://trello.com/c/lRXGNyzH/280-send-invite-to-fund-an-issue)

**Comment by sinharaksh1t** [comment]
Can I please have more information about what needs to be done for this issue?
The link (https://github.com/worknenjoy/gitpay/issues/222#issuecomment-449481839) in your comment above says "Card not found"

**Comment by alexanmtz** [comment]
@sinharaksh1t sorry this card is where the initial plan for this issue was opened, we use before to create the issue.

This is a good issue for you start cause it has a similar feature if you go in "I'm interested" button on the issue page on Gitpay:

<img width="651" alt="Screen Shot 2019-08-12 at 8 34 32 PM" src="https://user-images.githubusercontent.com/88840/62889004-c1e3d000-bd40-11e9-9692-dc14e82657b5.png">

You will create a new button as "I'm interested" with "Invite for funding", so the dialog will be the one designed that will trigger the action to send an invite with the information provided in this dialog, and you can follow this template:

Ps. The user needs to be logged, otherwise, it will ask for login as we have in the interested dialog.

```
Hello,

{username} invite you to contribute with ${value} for this issue.

{message}

You can add a bounty at {url}

```

Let me know if you have any additional questions and I will be happy to help 🙏 

And please follow how the existing feature cause this is very similar to the notification that we send when someone is interested in solve a task, but in this case it will send for the email filled in the form. You can see there's an invite button to invite a contributor, so it's a mix of both, and in this case is inviting someone to add bounties with the suggested price filled by who is inviting.

I will send you extra additional keys in order to test the invite e-mail with a Sendgrid env key.

**Comment by alexanmtz** [comment]
@sinharaksh1t some update on this?

**Comment by sinharaksh1t** [comment]
Hey @alexandreramosdev, I'm so sorry I haven't been able to work on this and I don't think I also have the bandwidth to finish this task anytime soon. I sincerely apologize for letting you down twice but I think my current full-time work is something I need to spend the majority of my time on.
Feel free to remove me as the assigned person for this task from me and assign it to someone if they are interested in doing it. I will revisit this repo as soon as my current work pressure reduces. So sorry once again, and I'm thankful to you for giving me the opportunity to work on this. 🙏

**Comment by alexanmtz** [comment]
Hello @sinharaksh1t , thanks for let me know. Let me know when you available again and feel free to show your interest on the issues you want to work with and good luck with your work!

**Comment by amrut07** [comment]
Hi @alexanmtz,
Can I work on this?

**Comment by alexanmtz** [comment]
Yes @amrut07 , I assigned you, feel free to start and let us know here if you have any question 🙏

**Comment by alexanmtz** [comment]
@amrut07 it's been a while without any updates from this, so I will remove you from this issue

**Comment by sachinpatil2** [comment]
Hi @alexanmtz,
Can I work on this?

**Comment by alexanmtz** [comment]
Yes, you will be assigned, and you will be assigned on Gitpay to receive the bounty: https://gitpay.me/#/task/210

**Comment by alexanmtz** [comment]
@TrickSantos is working on this right now

**Comment by VictorAlessander** [comment]
Greetings. This issue is available?

**Comment by alexanmtz** [comment]
Yes @VictorAlessander , I assigned to you: https://gitpay.me/#/task/210

**Comment by VictorAlessander** [comment]
PR created. Sorry my delay. I had some health issues over last four days ago and currently I'm still under recovering.

So, I need to report some things for this PR (#505)

1- I couldn't test the e-mail notification for invite (Mailchimp). I created an account to myself and added the api key, but somehow I didn't received any e-mail originated by my tests.

2- I refactored the task-invite component, creating a component called by task-assignment, but the state and methods that handle with state I kept into task component. I think that this way could be done with less changes, but I understand that can be do more too, so I'm open to change the PR if necessary.

3- I saw a little gramatical error, but I wasn't sure if I could fix this in the same PR. In the pic evidence, the text have a word **"thte"**.
> ![image](https://user-images.githubusercontent.com/21283066/76916146-5ba6c900-689e-11ea-9af5-e9dd21b31191.png)

**Comment by alexanmtz** [comment]
@VictorAlessander thanks for the update, and no problem, and I hope you get well soon :-)

We have a great progress here.

About your questions:

1- I couldn't test the e-mail notification for an invite (Mailchimp). I created an account to myself and added the API key, but somehow I didn't receive any e-mail originated by my tests.
_The email notifications are sent with Sendgrid, so I need to send you a temporary development key in order to receive the emails, and I will send you_

2- I refactored the task-invite component, creating a component called by task-assignment, but the state and methods that handle with the state I kept into task component. I think that this way could be done with fewer changes, but I understand that can do more too, so I'm open to change the PR if necessary.
_Thats good, for now, we need minor refactorings and the improvements are welcome_

3- I saw a little grammatical error, but I wasn't sure if I could fix this in the same PR. In the pic evidence, the text has the word "thte".
_thanks to find the error and fix_

We have some adjustments that we need now, cause I think there's a little mistake in the way we understand this issue. So I will make the comments on the PR.

**Comment by alexanmtz** [comment]
@VictorAlessander , your PR was merged, but I can see there's still a minor issue before we consider this completed.

You created a validation for the email in the email field, but I can still send it empty. So besides the mail validation, we need to check if the field is not empty before sending it.

So please create a new PR providing this solution so we can finish this 🙏

**Comment by VictorAlessander** [comment]
Created PR https://github.com/worknenjoy/gitpay/pull/576

**Comment by alexanmtz** [comment]
You changes were merged @VictorAlessander, thanks for the great contribution 🚀
