### ISSUE TITLE
Better flow to let contributors know about paypal and direct payments

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#227]
We will add extra info in the task view page

### Level
Beginner

### Current behavior
- We are facing a issue about the payment, the user isn't aware about how method the payment for a bounty was, and for this there's issues to activate the account. The screenshot is self explanatory, we need more info about that bounty. We have all the information, but this make it clear on the interface

### Expected behavior
Expected to show extra info about the task

### Screenshots
<img width="519" alt="screen shot 2018-12-22 at 1 22 33 am" src="https://user-images.githubusercontent.com/88840/50368352-1d7e0500-0588-11e9-955b-00b44f923113.png">

![task-details](https://user-images.githubusercontent.com/88840/62764227-abfab480-ba8d-11e9-9732-21f5504a9664.png)

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Better flow to let contributors know about paypal and direct payments](https://trello.com/c/xROaIBuQ/257-better-flow-to-let-contributors-know-about-paypal-and-direct-payments)

**Comment by robertkibet** [comment]
:tada: @alexanmtz

**Comment by alexanmtz** [comment]
Hello @robertkibet, you're now assigned 👍

**Comment by robertkibet** [comment]
@alexanmtz how can I reproduce this locally?

**Comment by alexanmtz** [comment]
@robertkibet, please follow the documentation on README and run the front-end and back-end locally. Then you can create users, import issues and try to add a bounty with the following credit card number for testing:
`4242424242424242`

So we will have a bounty and we can display this component.

If there's no payment you don't need to show anything

**Comment by robertkibet** [comment]
@alexanmtz 
https://github.com/worknenjoy/gitpay/pull/629
:tada: :tada: :tada: :tada:

**Comment by robertkibet** [comment]
@alexanmtz 
https://github.com/worknenjoy/gitpay/pull/629
Fixed lint :smile:
