### ISSUE TITLE
Send solution

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#228]
Send solution by providing a link (for a Pull Request for example) or uploading a file

### Why
We need a way to the contributors send the solution to be reviewed

### Level
Medium

### Requirements
 - This task needs to upload the files for a storage service that can be Amazon S3

### Screenshot
![task extras](https://user-images.githubusercontent.com/88840/50368289-68e3e380-0587-11e9-8f3b-79565fc75be6.png)

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Send solution](https://trello.com/c/vEUWM4BN/198-send-solution)

**Comment by sagarchaturvedi19** [comment]
Solution sample.

**Comment by alexanmtz** [comment]
We will close this for now to simplify to send solution by pasting a link. We need more design requirements
