### ISSUE TITLE
Make an offer for a task

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#237]
When an user is interested to develop a task, they can show interested by clicking in "I'm interested", but we need to know their suggestion and give some guidance with extra information

### Why
We want to know about the contributor opinion about the task bounty and send an different offer if for some reason they don't agree with the current offer

### Level
Medium

### Current behavior
- The user creates a task from an issue from Github or Bitbucket
- Other user can be interested to solve that issue
- He clicks in the "I'm interested" button on the task page
- A dialog appear to confirm
- The owner and the user receive an email telling about the next steps

### Expected behavior
- The user creates a task from an issue from Github or Bitbucket
- Other user can be interested to solve that issue
- He clicks in the "I'm interested" button on the task page
- A dialog appear to confirm
- The user can suggest a different bounty as well inform that he wants that task just to improve
- The owner and the user receive an email telling about the next steps

### Useful links
  - https://material-ui.com/

### How to solve this issue
 - You will need to store the information on the database creating new fields on the `Task` model to store suggested bounties, that will hold the reference to another model `Offers`. One Task has multiple offers, each one from each user.
 - The offer has a value that correspond to the value suggested and a flag to indicate that the task is for learning purposes
 - If the offer is send more than once for the same user, the offer will be updated
 - You should store in offer all the information from the dialog on the screenshot (`value`, `suggested_date`, `comment` and `learn`)
 - You will need to add on the related email template the info about the offer
 - You will need to hold the multi language with the translation that should be pretty straightforward based on the examples already implemented
 - You will need to create the proper reduces and actions that hold the actions for that model

### How to reproduce the user scenario

 - Create an user
 - Post a task
 - Create another user
 - Visit the same task
 - Click in 'I'm interested'
 - This dialog attached should be included

### Tips
- You will be more effective if follow the tests on the backend to validate the models
- Reuse the bounty suggestion component from the task page, or even create a new component that both component could use

### Screenshot
![interested offer](https://user-images.githubusercontent.com/88840/50363595-94a5a000-056c-11e9-84d3-d9c87e621f86.png)

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make an offer for a task](https://trello.com/c/FkTa79mP/204-make-an-offer-for-a-task)

**Comment by leonardohof** [comment]
codemill$100

**Comment by alexanmtz** [comment]
@leonardohof you we're assigned on Gitpay: https://gitpay.me/#/task/146

**Comment by alexanmtz** [comment]
Great contribution @leonardohof, It's working on production

🚀 🚀 🚀 🚀 🚀

**Comment by alexanmtz** [comment]
@leonardohof just to let you know I've made some changes cause the notifications by email was sent in inverse order, you can check here:
https://github.com/worknenjoy/gitpay/commit/fe62e4c45a16be033a17619933db8881093ce6b8

**Comment by leonardohof** [comment]
Ok, Sorry about that.
