### ISSUE TITLE
Preference buttons

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#25]
There's a bug when we click on the menu elements, because the active area don't cover all the menu as we can see here:

![screen shot 2018-06-04 at 2 28 27 am](https://user-images.githubusercontent.com/88840/40893031-24b023e4-679f-11e8-9c5e-a6a113a66a1c.png)

You can access this page at [https://gitpay.me/#/profile](https://gitpay.me/#/profile) (you need to be logged)

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/34

**Comment by alexanmtz** [comment]
@oliverbhz, if you're working on this already, please mark as interested here 
https://gitpay.me/#/task/34

So I can assign you and you will be able to follow the payment process

**Comment by oliverbhz** [comment]
Sorry for the delay, I marked you as interested.

**Comment by alexanmtz** [comment]
Merged and solved, thanks @lucianojfj 🥇
