### ISSUE TITLE
A nice feedback after import an issue to Gitpay

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#266]
Would be nice to have a more clear steps after an issue is imported to Gitpay.

Requirements:
- Only load on the first time the user add an issue to Gitpay

## See the screenshots:
![Desktop Copy 2](https://user-images.githubusercontent.com/88840/65995323-97d3a200-e495-11e9-91c8-92c74046c6bd.png)
![Desktop Copy](https://user-images.githubusercontent.com/88840/65995324-986c3880-e495-11e9-8838-c9c2bbb08c5c.png)
![Desktop](https://user-images.githubusercontent.com/88840/65995325-986c3880-e495-11e9-9515-856b82e92977.png)

## Assets
![add-bounties-illustration@2x](https://user-images.githubusercontent.com/88840/65995353-a3bf6400-e495-11e9-9253-4abfb23a6982.png)
![community-illustration@2x](https://user-images.githubusercontent.com/88840/65995354-a457fa80-e495-11e9-88ed-5539fbe66c9e.png)
![deadline-illustration@2x](https://user-images.githubusercontent.com/88840/65995356-a457fa80-e495-11e9-9809-0ea99709fc84.png)

**Comment by Alamin02** [comment]
Hi, can I try this?

**Comment by alexanmtz** [comment]
Yes @Alamin02 , You were assigned and please follow the project documentation to be able to run the project and develop this feature. If you need any help, feel free to comment here and happy coding 👨‍💻

**Comment by eduaugustus** [comment]
Hi, can i do this?

**Comment by alexanmtz** [comment]
@eduaugustus I assigned @Alamin02 to this, can you take another one?

**Comment by alexanmtz** [comment]
How about this one https://github.com/worknenjoy/gitpay/issues/222 @eduaugustus

**Comment by alexanmtz** [comment]
Hello @Alamin02 , some progress with this issue?

**Comment by Alamin02** [comment]
Hi, thanks for following up. I am using windows as my development machine. Whenever I run - `npm install`  I get the following errors - 

`
> node-sass@4.11.0 install C:\Users\alami\Documents\GitHub\gitpay\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall C:\Users\alami\Documents\GitHub\gitpay\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\alami\Documents\GitHub\gitpay\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.13.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n' +
gyp verb `which` failed     '    at getNotFoundError (C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\alami\Documents\GitHub\gitpay\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\alami\Documents\GitHub\gitpay\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\alami\Documents\GitHub\gitpay\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alami\\Documents\\GitHub\\gitpay\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
"--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\alami\Documents\GitHub\gitpay\node_modules\node-sass
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN babel-loader@7.1.2 requires a peer of babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@7.1.2 requires a peer of webpack@2 || 3 but none is installed. You must install peer dependencies yourself.
npm WARN karma-webpack@2.0.6 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-intl@2.6.0 requires a peer of react@^0.14.9 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-query-params@1.0.7 requires a peer of react@^15.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@1.12.0 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package cors is included as both a dev and production dependency.
npm WARN The package dotenv is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alami\AppData\Roaming\npm-cache\_logs\2019-10-29T15_56_37_756Z-debug.log
`

Sorry its a very long trace, but I don't know how much is the most important one.

**Comment by alexanmtz** [comment]
Hello @Alamin02 , can you try one of these solutions:
https://spin.atomicobject.com/2019/03/27/node-gyp-windows/ ?

**Comment by alexanmtz** [comment]
@eduaugustus, still interested to work on this?

**Comment by vinicius98s** [comment]
Hi everyone is there someone working on this? I would be willing to get this task

**Comment by alexanmtz** [comment]
No @vinicius98s , you can start to work on this one

**Comment by alexanmtz** [comment]
@vinicius98s , some progress on this issue?

**Comment by vinicius98s** [comment]
@alexanmtz I setup all the environment on the weekend, also created the modal, just need a better styling and the functionality to move between the steps, I'll try to get this frontend done at least this week

**Comment by vinicius98s** [comment]
Hey @alexanmtz  just to keep an update on this, I've made the frontend, any thoughts?

![01](https://user-images.githubusercontent.com/38966428/76710316-4a668c80-66e5-11ea-9acf-fa5410ea6c23.gif)

Now Im just wondering how can I get if it's the user's first task, is there already some information on the server that I can use?

**Comment by alexanmtz** [comment]
Great @vinicius98s ! 

For now, just a little adjustment with the main images, you need to switch the deadline image with the community image.

And about the information to display on the first task, I was looking for several solutions, and I will suggest one purely on the front-end, to avoid calling the back-end to retrieve the number of issues from that user, or any extra flag on the user to check this information.

We have here:
https://github.com/worknenjoy/gitpay/blob/master/frontend/src/actions/taskActions.js#L240

When we display the issue page, when the issue was imported successfully, we could send a query parameter here to activate the wizard, and use it together with LocalStorage to display only on the first load.

Let me know what you think and if you have any questions.

**Comment by alexanmtz** [comment]
Hello @vinicius98s, are you still working on this?

**Comment by vinicius98s** [comment]
@alexanmtz Yes, i'm sorry i didn't have much time at the past week but i will try to open a PR asap

**Comment by vinicius98s** [comment]
Hey, @alexanmtz I got some more things done, I fixed the image order, added the logic with the localStorage and also added the translation.
I just need to know what are exactly the actions for those buttons (Add bounties now and Set Deadline).

![Kapture 2020-03-29 at 17 38 39](https://user-images.githubusercontent.com/38966428/77860271-b6b4b600-71e4-11ea-9eaa-5f1d05d1b7f9.gif)

**Comment by alexanmtz** [comment]
Amazing @vinicius98s , great progress. The *Add bounties* and *Deadline* will close the modal and open the components of bounties and deadline, the same if you click in "Add bounties" and "Set deadline" in the menu bar.

**Comment by alexanmtz** [comment]
hello @vinicius98s, some update about this issue? You can send a Pull Request with your current progress?

**Comment by vinicius98s** [comment]
Hi @alexanmtz I'll try to send my PR complete later today
