### ISSUE TITLE
Fix the layout of offer

### ISSUE THREAD

**Issue by mthais** [worknenjoy/gitpay#267]
The goal of this issue is to do some changes to the layout of popup of the option "Tenho interesse" in the task area.

### Why
Is needed to have a layout according to with platform pattern.

### Level
Beginner

### Current behavior
When the developer is interested in a task and he clicks on the button "Tenho Interesse", the system is showing a popup up with some bugs.

### Expected behavior
The pop up that is showed to a developer that is interested in the task, should be fixed according to the proposed prototype.

### **Current  prototype**

![image](https://user-images.githubusercontent.com/27444220/50797190-1dd20c00-12bb-11e9-8f55-1d54d9f5fb81.png)

### **Expected prototype**

![whatsapp image 2019-01-04 at 21 47 14](https://user-images.githubusercontent.com/27444220/50796815-fb8bbe80-12b9-11e9-8d6e-a2f1726725fb.jpeg)

![49767795-41b12a80-fcda-11e8-9182-bdee7ab8cc83](https://user-images.githubusercontent.com/27444220/50797226-393d1700-12bb-11e9-937c-17c744a14867.png)

### How to solve this issue

- Fix the layout of pop up according to the expected prototype;

### How to reproduce the user scenario

 - Run the project locally;
 - Make a login;
 - Choose a task that has an "open status";
 - Click on the button "Tenho interesse";
 - The system will show the popup that needs of some adjust;

### What you will need to complete this issue
Extra requirements to complete the task

### Tips
Important things to know to better find the solution for this task

**Comment by alexanmtz** [comment]
🚀
