### ISSUE TITLE
Refactor in Task component

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#270]
The Task component is too big and need to split in minor components.

**Comment by alexanmtz** [comment]
Deployed and tested 🚀 🤖 

Thanks @VictorAlessander for the great contribution 🥇

**Comment by alexanmtz** [comment]
@VictorAlessander , when we choose a interested user it throws an error
<img width="1675" alt="Screenshot 2019-08-08 at 09 51 57" src="https://user-images.githubusercontent.com/88840/62685136-560d0a80-b9c2-11e9-85a2-7b24778795d6.png">

Can you check this?


@mthais I think you missed this test.

**Comment by alexanmtz** [comment]
@VictorAlessander , I fixed the bug and I will close this again, just check #394 to verify what was missing.

Thanks!

**Comment by VictorAlessander** [comment]
Sorry about this. I don't know how I let this pass.

**Comment by alexanmtz** [comment]
No problem @VictorAlessander , it was a big refactoring and you did a real good job 🤝
