### ISSUE TITLE
Find a bug and fix

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#272]
If you find a bug and fix it in a Pull Request you will receive a bounty.

Bugs found:
- insecure HTTP cookies: add secure flag
- missing HTTP security headers
- use seperate stylesheet for data-jss
- performance issue on Internet Explorer: website doesn't load

Please verify these bugs and propose a solution or a discussion if you don't agree with some item on this list

**Comment by Rbwebsol** [comment]
I am interested

**Comment by alexanmtz** [comment]
@Rbwebsol please [click here ](http://probot-invite.herokuapp.com/join/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3b3JrbmVuam95IiwiaXNzIjo1NTM1NTQsInJvbGUiOiJtZW1iZXIiLCJ0ZWFtcyI6WyIyODA0NDE5IiwiMjYzNzkyOSJdLCJpYXQiOjE1NDY0NzI4NjR9.iHSIS0XuvmvhwOROdkKw64i00PgzeK4e7h_yCxFh1YE)to be added to the team and I will assign this task for you

**Comment by lorenzdesmedt** [comment]
- insecure HTTP cookies: add secure flag
- missing HTTP security headers
- use seperate stylesheet for data-jss 
- performance issue on Internet Explorer: website doesn't load

**Comment by alexanmtz** [comment]
We have now issues open related to the bugs reported, we will close this for now, thank you
