### ISSUE TITLE
Create sequelize seeds to allow the initial setup of the database

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#312]
Create Sequelize seeds, with users and tasks to help developers with the initial setup.

You can follow this tutorial: http://docs.sequelizejs.com/manual/tutorial/migrations.html

### Why
We need a initial setup with at least two users and two tasks

### Level
Level required to conclude this issue

### Current behavior
When start the project, we need to create by hand the first users and task

### Expected behavior
We should run a seed to setup a initial data

**Comment by alexanmtz** [comment]
I've created a seed for testing but for some reason is not storing on the database, you know the reason @wharley ?

https://github.com/worknenjoy/gitpay/blob/master/migration/seeders/20190326142803-roles.js

https://github.com/worknenjoy/gitpay/blob/master/migrate.js#L51

https://github.com/worknenjoy/gitpay/blob/master/package.json#L12

**Comment by VictorAlessander** [comment]
Greetings.

Can I contribute in this issue?

**Comment by alexanmtz** [comment]
great @VictorAlessander, I assigned to you this issue, so you can solve it. I started already to implement and we have a command to run seed on npm in package (https://github.com/worknenjoy/gitpay/blob/master/package.json#L12)

And we have some seeds: https://github.com/worknenjoy/gitpay/tree/master/migration/seeders

But isn't working, so the issue is enable locally and maybe add example tasks if possible

**Comment by VictorAlessander** [comment]
I tested on my workspace the command `npm run seed` and only not work if the command `npm run migrate` wasn't executed before.

**Comment by alexanmtz** [comment]
That's great @VictorAlessander, looking forward to review it ✋

**Comment by VictorAlessander** [comment]
Pull Request created.

**Comment by alexanmtz** [comment]
Great @VictorAlessander , it was approved and merged and is already in the code base, thanks for your contribution 🚀 🥇
