### ISSUE TITLE
Register Bank Account

### ISSUE THREAD

**Issue by laugustofrontend** [worknenjoy/gitpay#314]
Hello, I'm trying to register my bank account, but this one giving error, I get to the end but it does not record, it happens the banks nubank and inter bank, which are the accounts that I have

### Why
Register bank account of users

### Level
Advanced

### Current behavior
![screenshot from 2019-01-31 21-30-35](https://user-images.githubusercontent.com/7988674/52092823-0e836d00-25a0-11e9-9b8e-50e6e825948e.png)
![screenshot from 2019-01-31 21-30-50](https://user-images.githubusercontent.com/7988674/52092886-4c809100-25a0-11e9-8b99-e440d5902495.png)

### Expected behavior
It is expected that after the registration the information will be persisted in the bank and shows the message that the account is registered

### How to reproduce the user scenario
- Sign in to My Account
- Payment confirmation
- Try to register a bank

**Comment by alexanmtz** [comment]
@laugustofrontend have you tried to fill with numbers only, without `-`?

**Comment by VictorAlessander** [comment]
My Nubank account was successfully registered without "-"

**Comment by VictorAlessander** [comment]
On **account number**, I received the hint text saying "Only digits".

@alexanmtz , you can check this field? I can't remove the registered bank account to confirm the information.

**Comment by alexanmtz** [comment]
@VictorAlessander Good! So we have this verification and for account routing we cant apply the same cause I remember some issue with Banco do Brasil

**Comment by alexanmtz** [comment]
We updated this account manually and I will close this issue for now
