### ISSUE TITLE
Unable to access the payment setting

### ISSUE THREAD

**Issue by raulvictorrosa** [worknenjoy/gitpay#346]
### Current behavior
![Capture2](https://user-images.githubusercontent.com/13530065/55162031-a8513b80-5145-11e9-955e-ca8d5e4f0f95.PNG)

When clicking on payment settings on page Account -> Preferences it gives me the page bellow and after shows me a white page.

![image](https://user-images.githubusercontent.com/13530065/55162070-c159ec80-5145-11e9-97ef-43fc7c3edf8f.png)

### Expected behavior
Show the Payment Setting

### usefull links
This is the logs that shows me on console.
[gitpay.me-1553717106570.log](https://github.com/worknenjoy/gitpay/files/3018182/gitpay.me-1553717106570.log)
[gitpay.me-1553717135323.log](https://github.com/worknenjoy/gitpay/files/3018183/gitpay.me-1553717135323.log)

**Comment by alexanmtz** [comment]
@raivitor I think I fixed with #350

Can you test and try to setup your payment?

**Comment by alexanmtz** [comment]
I will close this now and the bug seems to be fixed
