### ISSUE TITLE
Sign-up form validation

### ISSUE THREAD

**Issue by mthais** [worknenjoy/gitpay#349]
When the user leaves the fields empty and click on the button "Signup", the system shows an error message.

### Why

The system should show theu user the validation message showing that the fields are empty.

### Level
Medium

### Current Behavior

When the user doesn't insert the information on the fields on the SignUp screen and click on the button "Signup", the system shows an error message. (See the screenshot bellow)

### Expected behavior

When the user doesn't insert the information in the fields and click on the button "Signup", the system should show a validation message.

### Useful links
N / A

### Attached Screen Capture

**Current Behavior**

![Screen Shot 2019-04-09 at 11 39 10](https://user-images.githubusercontent.com/27444220/56526963-583a7e80-6523-11e9-91e5-09263cbb7642.png)

### How to resolve this problem
- Run the project locally;
- Access the login functionality;
- Insert the validation message in the fields on the Signup functionality.

### How to Play the User Scenario

- Access the platform;
- Click on the button "Signin" at the top;
- Click on the button "Signup";
- The system shows the Sign up pop up; 
- Leave the fields "Name", "Email" and "Password" without any information and click on the button "Signup";
- The system shows an error message;

### What you will need to complete 

- The system should show the user that it is required  to fill in the form.
- It is necessary to follow the message pattern contained on the system to fill in  what is  required. 

### Tips

When you finish the task, send us A print screen of the test done by you.

**Comment by alexanmtz** [comment]
Fixed and deployed 🚀
