### ISSUE TITLE
Option to create account is in error

### ISSUE THREAD

**Issue by mthais** [worknenjoy/gitpay#36]
Description

When I click to create an account, the system showing the success alert message, but the system don't reload the page and nothing happened.

### Screenshot attached

![criar conta](https://user-images.githubusercontent.com/27444220/41498565-4f3b9830-7147-11e8-85a3-cb2bc48ead98.png)

### How to reproduze the user scenario

1- Access your account on Gitpay;
2 - Choose the option "Criar Conta";
3- The system showing the success alert message, but the system don't reload the page and nothing happened.

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/25

**Comment by alexanmtz** [comment]
Your e-mail is null cause you are with your public email disabled:
https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope

**Comment by alexanmtz** [comment]
@mthais ainda não conseguindo ativar a sua conta bancária? Tem um pagamento por esta tarefa lá que gostaria de testar para a sua conta

**Comment by mthais** [comment]
@alexanmtz Agora consegui ativar a conta com sucesso.
![image](https://user-images.githubusercontent.com/27444220/42401857-f8bc64dc-814d-11e8-8e55-412f6eaaf55f.png)

**Comment by alexanmtz** [comment]
Great! I will approve the payment @mthais 

🚀 🚀 🚀 🚀 🚀 🚀 

Thanks for you patience
