### ISSUE TITLE
Mobile browsing with a hamburger menu

### ISSUE THREAD

**Issue by mthais** [worknenjoy/gitpay#379]
We need to have a better experience in mobile browsing with a hamburger menu, because currently it is breaking the layout on mobile version.

### Why
The menu of the mobile version don't support all items, and it's breaking the layout.

### Level
Medium

### Current behavior
When the user access Gitpay platform on mobile, the system is showing a menu with broke layout.

### Expected behavior
When the user access the Gitpay platform on mobile, the system should show the hamburger menu as the reference below.

### useful links
The reference to solve this issue is the following:
https://alexanmtz.github.io/material-sense/#/

### Screenshot attached

**Current behavior**
![WhatsApp Image 2019-07-01 at 12 37 32](https://user-images.githubusercontent.com/27444220/60449029-2ae20f00-9bfd-11e9-8d2e-b2e284c440f0.jpeg)

### How to solve this issue
- Add breakpoints form mobile
- Create a logic that hide the menu and display the hamburguer with a side list
- Check the reference of the sample project

### How to play the user scenario
- Run the project locally

### What you will need to complete this issue
No extra requirements to complete this task

### Tips
Check https://github.com/alexanmtz/material-sense/blob/master/src/components/Topbar.js to see how this solution was achieved with React Material UI with this template

**Comment by sinharaksh1t** [comment]
Is anyone working on this issue? If not, I would like to try my hands on it.

**Comment by mthais** [comment]
@sinharaksh1t Yes, we have another person working on this issue. You can check other issues if you'd like. I'm looking forward to having  you working with us on these issues!

**Comment by sinharaksh1t** [comment]
Cool, thanks. I'll check other issues then.

**Comment by alexanmtz** [comment]
@sinharaksh1t , actually you can start work on this, cause the other contributor that was working on these is having issues, please take a look in a good reference from this project of how to do with Material-UI: https://github.com/alexanmtz/material-sense/blob/master/src/components/Topbar.js

Let me know if you have any question on issue and you were assigned

**Comment by sinharaksh1t** [comment]
Sounds good. I'll start working on this after my work today.
Just curious what would be the deadline to resolve this issue? Also, are there any contributing guidelines you'd like me to follow before I start working on this?

**Comment by alexanmtz** [comment]
Great @sinharaksh1t 🎉 

This is a high priority bug, so it should be fixed as soon is possible, but it suppose to be pleasure for you and a good issue for learn as well, so you think one week is enough?

We have these fresh guidelines: https://github.com/worknenjoy/gitpay/blob/master/CONTRIBUTING.md

And because this is a simple front-end task, you will not need any extra requirements to run the project locally, just follow the documentation: https://github.com/worknenjoy/gitpay/blob/master/README.md, and once you have running locally, you can make the proper changes and send a PR from a branch in your fork, there's a template to follow already.

Let me know if you need any help 👍

**Comment by sinharaksh1t** [comment]
Awesome, thanks @alexanmtz. I'll go over the links you provided and get this done within 1 week. I'll keep providing regular updates if things don't go as planned, but that's highly unlikely.
Just last question for now before I begin - do you prefer commits squashed? Or would you like an unaltered complete history of all the commits?

**Comment by alexanmtz** [comment]
@sinharaksh1t great! Thanks for let me know. Your question is a good on to improve our contribution guidelines, you can commit normally on your branch and we can squash when we approve the Pull Request.

**Comment by sinharaksh1t** [comment]
Sounds good, thanks @alexanmtz.

**Comment by sinharaksh1t** [comment]
I ran `npm run test` on master branch itself and I found the following error:
![Capture](https://user-images.githubusercontent.com/28585848/61573837-f1692a80-aa69-11e9-8a78-21f77f18f90b.PNG)

Should I try to fix them in another PR as well or just let them be?

**Comment by alexanmtz** [comment]
@sinharaksh1t you can run `npm run lint-fix` to solve this and you can send in the same PR

**Comment by sinharaksh1t** [comment]
@alexanmtz - Sorry about the delay. I couldn't work on this over the entire week due to my full-time work schedule. I just spent some time on this today and the progress is tracked no my branch here: https://github.com/worknenjoy/gitpay/compare/master...sinharaksh1t:sinharaksh1t/issue-379-hamburger-menu
The finish line is still far coz I still need to do a lot of cleanups and of course the actual work of enabling hamburger menu. But I've at least been able to pick the right hook and figured out how I'm going to solve this problem.
I should be able to finish it by Sunday for sure. Hope that's okay, and once again, I apologize for the delay.

**Comment by alexanmtz** [comment]
Hello @sinharaksh1t , thanks for let me know and great that you made progress! Looking forward to see your pull request 🙏

**Comment by alexanmtz** [comment]
@sinharaksh1t , some update on this?

**Comment by alexanmtz** [comment]
@sinharaksh1t , this issue was assigned to @alexandreramosdev on Gitpay. Feel free when you have time to solve any other issue and thanks for the effort.

**Comment by alexandreramosdev** [comment]
@alexanmtz I'll start start solving this issue. If i have question I'll send a mensage to you! ;)

**Comment by sinharaksh1t** [comment]
Hey @alexanmtz I'm so sorry for not responding on time. I feel really guilty that I took up this task and I wasn't able to complete it on time. I didn't mean to ghost you like this. Just way too many things happening all of a sudden IRL.
Thank you @alexandreramosdev for taking over. 🙏

**Comment by alexanmtz** [comment]
No problem @sinharaksh1t , this is a bug so we need to solve asap as affect the mobile experience. I can suggest you to do the #222 that is a good first issue. What do you think?

**Comment by alexanmtz** [comment]
Great @alexandreramosdev , good to have you contributing again 🎉

**Comment by sinharaksh1t** [comment]
Thank you @alexanmtz for understanding. I truly appreciate it. I will check #222 out and post more questions if necessary. Thanks for giving me another chance. I look forward to working on that issue.

**Comment by alexandreramosdev** [comment]
@alexanmtz I made it as simple as possible not to increase the complexity of the component.

**Comment by alexanmtz** [comment]
@alexandreramosdev this is not exactly the solution we were expected as the reference we provided, but you did in a simpler, efficient and beauty way of solving this. Many thanks @alexandreramosdev 🎉 🎉 🎉 🎉 🎉 🎉 for the great solution and contribution 🙏

**Comment by alexanmtz** [comment]
There's still minor issues @alexandreramosdev , if you click on the menu it should change state like the screenshot

And when we scroll with the mobile menu opened, it scroll the screen behind.

But I decided to merge it cause currently it was breaking the layout the way before.

![5c461332c8c0fdfa83316562_cover](https://user-images.githubusercontent.com/88840/64111948-2e714e00-cd86-11e9-8e9f-bca5f6f71ea4.gif)

**Comment by alexandreramosdev** [comment]
Ok!  change state in hambuguer is easy !  I will made today !
