### ISSUE TITLE
Add db seed info to readme

### ISSUE THREAD

**Issue by srkyaganti** [worknenjoy/gitpay#410]
The documentation contains setup instructions for databases. For a new user to test changes related to maintaining a lot of users, it becomes a tedious task to create users or as a matter of fact data in all the tables for testing. 

I would like to propose a seeding script that populates data in all the database tables starting with users 

### Why
Motivations when solve this issue
- Reduce break-in period for new developers to contribute

### Current behavior
- No db auto-populating feature exists

### Expected behavior
- Create scripts that populates rows in database tables as required

### usefull links
  - I first came across this feature when working on Laravel: https://laravel.com/docs/master/seeding

### Screenshot attached
- N/A

### How to solve this issue
 - Create a script that can be used to populate the database with multiple configurations

### How to reproduce the user scenario
 - N/A

### What you will need to complete this issue
- N/A

**Comment by alexanmtz** [comment]
Hello @srkyaganti , thanks for contribute adding an issue. We have a seed here:
https://github.com/worknenjoy/gitpay/tree/master/migration/seeders

Maybe you should documented more, you can run the seeds with:
`npm run seed` and `npm run seed-test` for tests

**Comment by srkyaganti** [comment]
got it, thanks

**Comment by srkyaganti** [comment]
Sorry for accidentally closing it. Will submit a PR soon.

Thanks,
Srikar

**Comment by alexanmtz** [comment]
Fixed with #412 , thanks @srkyaganti 🥇
