### ISSUE TITLE
Issue page interest redesign

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#425]
We have a new page redesign for users interested to solve an issue. This page should now follow the screenshot. It's a task to redesign an existing component.

### Why
We want to improve the experience to apply to solve issues, make offers and understand how to work on Gitpay, as well as an agreement before confirming interest to solve an issue.

### Level
Beginner, and cover only front-end

### Current behavior
This is the current page that you can reach by clicking in any issue inside the platform like https://gitpay.me/#/task/290

<img width="711" alt="Screen Shot 2019-10-03 at 3 51 22 PM" src="https://user-images.githubusercontent.com/88840/66663949-f514e380-ec4b-11e9-9fec-db7ecfb9197e.png">

### Expected behavior
This is how the page should be presented.
![interested-1](https://user-images.githubusercontent.com/88840/66663734-846dc700-ec4b-11e9-8ece-b09257d56b2c.png)
![interested-2](https://user-images.githubusercontent.com/88840/66663730-820b6d00-ec4b-11e9-8c4a-b4054c8f2c5a.png)

### Useful links
  - We use Material-UI, so to reach the desired design, follow the guidelines: https://material-ui.com/

### Assets
Images needed to build this page:
![bounty-image](https://user-images.githubusercontent.com/88840/66663439-09a4ac00-ec4b-11e9-92e7-15e25bdf2056.png)

### How to solve this issue
 - [Read the docs first](https://github.com/worknenjoy/gitpay)
 - Run the project locally
 - Run the seeds (check on the documentation)
 - Create your account locally
 - Access the task created
 - Make an offer or click in "I'm interested"

### What you will need to complete this issue
You need to know react to make the proper changes, as a little of CSS (JSS) to adapt the design.

### Tips
We follow the [Material UI design](https://material-ui.com/) guidelines, so you can use the framework to refactor this code to the new design.

## What you will learn
You will see how a page with dialog components works, get a good understanding of react and ui libraries like Material-UI

**Comment by SebastianLF** [comment]
Can I work on this?

**Comment by alexanmtz** [comment]
Hello @SebastianLF , we already received a Pull Request from this one #428 , probably will be merged soon, so feel free to take another one avaiable from our issues.

**Comment by alexanmtz** [comment]
Merged #438 and deployed 🚀

thanks @okansahin for this contribution

**Comment by SebastianLF** [comment]
> @SebastianLF are you still interested to work on this? We have #431 on the progress that you could continue to work and use as a reference.

Sorry I havent received the notification. :/
