### ISSUE TITLE
When add a bounty, choose between plans and apply to final price

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#451]
We have different plans when adding a bounty, as the screenshot

1. 8% Fee for open source projects
2. 18% For private projects
3. 30% with support 

We have saved the project type (public or private) and we need to set automatically 8% for open source and disable 18%, as for private projects we disable open source and set automatically 18% fee.

Please add the plans scheme on the database as an attribute for `task`, with an associated model `plans`, which record the plan chosen, and the associated model will store the information about the plan.

### Why
We have clients that need our support to assign someone to the issue and review, and another simple plan for open source maintainers to use Gitpay to paid bounties to solve their issues.

When the plan is 30% with support, send an e-mail to our `notifications@gitpay.me` to inform that support was requested

### Level
Medium

### Current behavior
- We don't change the final price based on a fee
- We have a fixed 8% fee for each transaction to the destination account

### Expected behavior
- Add options to choose between different plans when adding a bounty
- Apply this fee to the final price

### Screenshot attached
![Desktop Copy](https://user-images.githubusercontent.com/88840/74192908-b96c4380-4c56-11ea-9e2e-82b0e070f4d3.png)

### How to solve this issue
 - Apply fees and update final prices based on the chosen plan

### How to reproduce the user scenario

 - Signup as a user
 - Import issue
 - Add a bounty

### What you will need to complete this issue
- You will need Stripe development keys to test payments

### Tips
- Use the Material UI components to create the UI elements
- Use material UI icons to place icons and their variations

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement fees](https://trello.com/c/zTJdjhRm/391-implement-fees)

**Comment by arrudaricardo** [comment]
@alexanmtz can I work on this issue?

**Comment by alexanmtz** [comment]
@arrudaricardo this issue is on Gitpay: https://gitpay.me/#/task/314 and someone were assigned to it, it's almost reaching the deadline, so let's see how it goes.

**Comment by arrudaricardo** [comment]
@alexanmtz Alright, thanks.

**Comment by arrudaricardo** [comment]
@alexanmtz  Just to confirm, since users can make many order for each task each order should have a fix plan? or each order created should have a specific plan ? In this case plan should be an attribute for the Order and not for task ?
