### ISSUE TITLE
[GitHub API] Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#452]
On February 10th, 2020 at 21:42 (UTC) your application (Gitpay) used its `client_id` and `client_secret` (with the User-Agent octonode/0.3 (https://github.com/pksunkara/octonode) terminal/0.0) as part of a set of query parameters to access an endpoint through the GitHub API:

https://api.github.com/repositories/481872/issues/10022

Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated and will be removed July 1st, 2020.

Depending on your API usage, we'll be sending you this email reminder at most once every 3 days.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

**Comment by alexanmtz** [comment]
@arrudaricardo now we had an error em production when fetching an issue:

```
github response error
Apr 14 01:03:32 gitpay app/web.1 TypeError: userExists is not a function
Apr 14 01:03:32 gitpay app/web.1     at requestPromise.then (/app/modules/tasks/taskFetch.js:77:41)
```

Maybe we miss to change here?
https://github.com/worknenjoy/gitpay/blob/master/modules/tasks/taskFetch.js#L70

can you take a look on this, please?

**Comment by alexanmtz** [comment]
@arrudaricardo It's really weird, cause the issue only happens in production, and maybe is not related to your changes

**Comment by alexanmtz** [comment]
Don't see related, let's keep this closed 👍

**Comment by arrudaricardo** [comment]
@alexanmtz I don't think is related, but I gonna take a look, gonna try to reproduce the error locally.

**Comment by alexanmtz** [comment]
@arrudaricardo this is happening only in production and I'm working in a temporarily fix 🙏
