### ISSUE TITLE
Wrong redirect when trying to login locally in a docker container

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#460]
Login fails when running on a docker container for a Linux environment.

### Screenshot attached
![Screenshot from 2019-10-28 22-24-52](https://user-images.githubusercontent.com/88840/74651033-4184a880-5183-11ea-99de-2f01ba963ef8.png)

**Comment by kandalf** [comment]
@alexanmtz I cannot start the docker containers on Arch Linux. I'm getting this error:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/43977/75103147-a43bd100-55d5-11ea-8668-22fe6da1ab32.png">

Just for what it's worth it works on MacOS Mojave with Docker Desktop Community Edition 2.2.0.3

Any clue about what I might be missing?

**Comment by kandalf** [comment]
Here's the same running on MacOS:
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/43977/75103236-cf72f000-55d6-11ea-8bf5-10d3440b1969.png">

This seems to be some frontend app dependency that might bot be resolving properly on Linux, but can't tell for sure, I'm no familiar enough with the app.

**Comment by alexanmtz** [comment]
Hey @kandalf , thanks to report this issue. I verified the module and everything is right, the module is on `package.json`, on `package.lock` and it's imported correctly.

I tried to search and I found this: https://stackoverflow.com/questions/49118005/webpack-unable-to-resolve-node-module-in-docker-image

Maybe try this?

**Comment by kandalf** [comment]
Hi @alexanmtz It's not only happening on docker, it happens on Linux.
`docker-compose up` didn't create a volume, so there's nothing I could delete as that post suggests.

I'm trying to run `npm run dev` directly on the host (up to date Arch Linux) and I'm getting the same error

**Comment by kandalf** [comment]
Alright, I got it working. The problem was that `invert-color` is not a dependency of the frontend app itself. IMO, it should be listed in the `frontend/package.json` as well.

**Comment by alexanmtz** [comment]
Great catch @kandalf 🎉 

Yeah, it is used on the front-end on the React application.

So let's proceed and let's have this included in your PR.

**Comment by kandalf** [comment]
@alexanmtz I'm still unable to migrate the database following the instructions, even when the connection information is OK since I can connect to the database using the same credentials with `psql`

![gitpay_migrate](https://user-images.githubusercontent.com/43977/76480434-68827300-63ed-11ea-9022-2ed362e5f0d4.gif)

Feel free to re-assing this issue, since it's taking way longer than anticipated and because of reasons that has nothing to do with the original problem

**Comment by alexanmtz** [comment]
@kandalf let's extend the deadline.

And thanks to clarify your issue.

Please try to set your password to `postgres`

As we expected in our config: https://github.com/worknenjoy/gitpay/search?q=postgres&unscoped_q=postgres

Let me know if works 🤞

**Comment by kandalf** [comment]
@alexanmtz I changed the password in `config/config.js` and `config/secrets.js`, that worked, not sure which one did the trick, but I just wanted to move on. This shoud be better documented, but it's out of the scope of this ticket.

I finally got the app up and running, and could reproduce the issue. I'll start looking into it now if you think it's OK.

**Comment by kandalf** [comment]
Alright, PR sent. The issue was really simple, too bad it took too long to to get the app up and running.
Instructions for docker should be added in the README.
Maybe a follow-up PR for that?

**Comment by alexanmtz** [comment]
Great @kandalf, and a great catch, yeah, sad about the environment but good that we could find an easy solution in the end.

Feel free to update the documentation in another PR 👍 

Your solution was merged, thanks for contributing 🚀
