### ISSUE TITLE
Unable to access the payment setting [depreacation]

### ISSUE THREAD

**Issue by FrancoisJULIENNE** [worknenjoy/gitpay#462]
Issue #346 is always present, regression ?

Current behavior
![image](https://user-images.githubusercontent.com/190781/74900370-d8c64780-539f-11ea-96e0-24be331ec2ea.png)

When clicking on payment settings on page Account -> Preferences it gives me the page bellow and after shows me a white page.

![image](https://user-images.githubusercontent.com/190781/74900388-e976bd80-539f-11ea-946c-94a441b3aff8.png)

Expected behavior
Show the Payment Setting

usefull links
This is the logs that shows me on console.
[gitpay.me-1582171676631.log](https://github.com/worknenjoy/gitpay/files/4228749/gitpay.me-1582171676631.log)

Browser : Chrome Version 80.0.3987.106 (Build officiel) (64 bits)
OS: Windows 10

**Comment by alexanmtz** [comment]
@FrancoisJULIENNE is not the same issue, now this issue happens cause Stripe change the APi and we did an update, but it's not working as expected.

What we can do now is handle the 500 error and provide a message with error, avoiding the blank screen, what do you think? You want to work on this until we have a position from Stripe support?

**Comment by alexanmtz** [comment]
So to solve this issue we should provide a friendly error page instead of a blank screen when the API call returns 500.

**Comment by alexanmtz** [comment]
Maybe #502 will help to degrade gracefully this

**Comment by alexanmtz** [comment]
I think this issue was solved from Stripe and we fix some issues with translations from our side 👍
