### ISSUE TITLE
Add new labels as filters on "Explorer tasks"

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#465]
Add extra labels on Explorer tasks, to show issues with bounties and contributions
(issues without bounties).

We need to highlight that new labels add new filters rather than select just one option. So we can have as example issues with `In progress` filter with `Contribution`.

### Why
We want to filter with extra filters, `$` for issues with bounties and `Contributions` to list issues without bounties. 

### Level
Easy

### Usefull links
  - https://github.com/reduxjs/reselect

### Screenshot attached
![task-explore-labels](https://user-images.githubusercontent.com/88840/75295455-fd507280-582a-11ea-825a-ed30c6c1815f.png)

### How to solve this issue
 - Add new selectors and take care of the redux state to efficiently filter issues

### How to reproduce the user scenario

 - Sign in a new user
 - Import an issue
 - Check filters

**Comment by blarcmann** [comment]
Can I please have more information about what needs to be done for this issue?

**Comment by alexanmtz** [comment]
hello @blarcmann , you need to basically extend our existing filters with react selectors, providing an interface to apply these filters as on the screenshots.

Here is the logic https://github.com/worknenjoy/gitpay/tree/master/frontend/src/selectors used to filter our existing list (with status open, in progress and done), and from that selectors renders on the components on the interface.

You need to add the filters to check if there are bounties for that issue and if there are no bounties, and sorting this list. This issue requires front-end knowledge only.

Let me know if have any further questions.

**Comment by blarcmann** [comment]
Hi @alexanmtz, can you add me please, so I can make my PR... I'm currently getting 403.

**Comment by alexanmtz** [comment]
@blarcmann, are still work on this?

**Comment by alexanmtz** [comment]
@blarcmann , we will make this issue available again as we didn't have any response 👍

**Comment by VictorAlessander** [comment]
Greetings, @alexanmtz.

During the development of this issue, I may found a bug.

When a label filter is selected and have a page refresh, the label and the path of page still are the same but the content in task list is referenced to all tasks. Example:

- Selecting label filter 'Closed';
- Now in the task list I have all tasks closed;
- I will refresh the page for some reason;
- Now, I still have the label filter 'Closed' selected, but the results in task list belongs to 'all' filter label.

First: This is really a bug?
Second: If yes, there's an issue already open to fix this?
Third: If not, can I fix this using this issue or I have to create a specific issue?

**Comment by alexanmtz** [comment]
Yeah @VictorAlessander, this seems an issue and if it is possible you can fix it together with this.
