### ISSUE TITLE
Notify all interested users when someone is assigned

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#466]
When someone is assigned to an issue, all the interested users who follow that issue should be notified with a generic email. 

This is the template email:

```
Hello {{name}},

The user {{username}} was assigned to {{title}} - {{url}}, an issue that you were interested.

Don't worry, you can look for other issues available.
 
Thanks,
Gitpay Team

----------------------
https://gitpay.me (Web)
tarefas@gitpay.me (Email)
Worknenjoy Inc., 2035 Sunset Lake Road #Suite B-2, Newark, DE 19702 (Mail)
```

### Why
We need to notified all users interested when someone is assigned, in order to communicate the status with all interested users.

### Level
Beginner

### Current behavior
Currently, when someone is assigned, all the interested users are not aware that someone started on that issue.

### Expected behavior
When a user is assigned to an issue, all the interested users should receive an email so they know that someone was chosen to solve that issue.

### How to solve this issue
 - You should go on mail functions on the node server
 - You can debug putting the email content on the console, cause the emails are sent with Sendgrid, and it requires API key.

### How to reproduce the user scenario

 - Create an User
 - Import an issue
 - Create another two users
 - One of these users show interest
 - With the first user, you assign one
 - The other interested should receive a notification

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notify all interested user - publish a task update](https://trello.com/c/bpBDxj5a/682-notify-all-interested-user-publish-a-task-update)

**Comment by arrudaricardo** [comment]
This issue exists and I am willing to work on this.

**Comment by alexanmtz** [comment]
Great @arrudaricardo, I will assign you to this, and let me know if you need any help.

**Comment by alexanmtz** [comment]
@arrudaricardo , are you still working on this issue?

**Comment by arrudaricardo** [comment]
Yes, I gonna make a PR latter today.

**Comment by alexanmtz** [comment]
Merged and deployed 🚀 , thanks for the contribution @arrudaricardo
