### ISSUE TITLE
Cannot start front-end server on Ubuntu following documentation

### ISSUE THREAD

**Issue by OmegaPointZero** [worknenjoy/gitpay#490]
Description 

### Why
Documentation regarding how to start and run the front-end server does not work on Ubuntu machines.

### Level
Low

### Current behavior
Attempting  to run npm run dev per documentation to start the front-end server results in `npm ERR! missing script: dev` on Ubuntu machines.

### Expected behavior
The front-end server begins to run without error

### Screenshot attached
![Screenshot from 2020-03-09 21-39-01](https://user-images.githubusercontent.com/12289197/76280336-c593f280-624e-11ea-8f9b-f21fc9db2782.png)

### How to solve this issue
Update documentation or replace the missing "dev" script

### How to reproduce the user scenario
+ Install and initialize PostgreSQL server on Ubuntu machine per documentation specifications
+ run `npm install`.
+ Run database seeding and migration operations and test
+ Run testing scripts to be sure everything else is working
+ Run the command `npm run dev` (One can run `npm run start:dev` per documentation for back-end server without issue, running `npm run dev` either before or after create the same issues.

### What you will need to complete this issue
Either uploading the missing script or updating the documentation to reflect the proper script to run.

**Comment by alexanmtz** [comment]
@OmegaPointZero are you running on `frontend` folder? It suppose to start from there, if you're running on the root folder, it suppose to run the back end with `npm run start:dev`

**Comment by alexanmtz** [comment]
To be solved with #842
