### ISSUE TITLE
Add current deadline and an option to remove deadline

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#496]
When an issue has a deadline, we should open the current value when we open the deadline field, and we need to have a way to disable the deadline to set it to empty again.

### Why
It's a bug that happens for tasks that are recurring, like this one:
https://gitpay.me/#/task/156
https://github.com/worknenjoy/gitpay/issues/247

### Level
Beginner

### Current behavior
Now the panel to set deadlines is not loading the current value and there's no way to unset deadline

### Expected behavior
The current value for that issue should be pre-filled on the date form, and an option to unset date along with _Save date_ button

### Screenshot attached
<img width="1065" alt="Screenshot 2020-03-17 at 13 57 46" src="https://user-images.githubusercontent.com/88840/76858677-3727fe00-6858-11ea-8880-1e2663731728.png">

### How to solve this issue
 - Check the set deadline form
 - Make sure it loads the current deadline
 - Update task with empty deadline to be able to unset deadline

### How to reproduce the user scenario
- You should run the project locally
 - Register your user
 - Import an issue
 - And set deadlines on the Task page you just created

### Tips
You can clear the deadline by adding a button 'Clear deadline' before the save button

**Comment by aryanvaid2108** [comment]
Hi, I want to work on this issue.

**Comment by alexanmtz** [comment]
Hello @aryanvaid2108, you're now assigned and you can start to work on this issue 👍

**Comment by aryanvaid2108** [comment]
Hi Alexandre,
I have installed the project on my local machine, and I have been able to
successfully run the front end. I'm kind of confused about the other stuff
that I need to install and run, I would really appreciate some help.

Thanks,
Aryan Vaid

**Comment by alexanmtz** [comment]
Please follow the steps to reproduce the user scenario:

### How to reproduce the user scenario
1. You should run the project locally
2. Register your user
3. Import an issue
4. And set deadlines on the Task page you just created

**Comment by alexanmtz** [comment]
Partially solved and the deadline will be reviewed
