### ISSUE TITLE
Who is using Gitpay component on home page

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#498]
Create a component to list our clients on our home page. It should be added to the sessions on the top menu as well. For now, the component will receive paths for images and a link to the project.

### Why
Let's start to highlight our clients from projects using Gitpay

### Level
Beginner

### Useful links
  - https://material-ui.com/

### Screenshot attached
![Gitpay - who is using - Desktop HD](https://user-images.githubusercontent.com/88840/76864964-4744db00-6862-11ea-8da9-7f4ce0902940.png)

### Assets
![grafana-logo](https://user-images.githubusercontent.com/88840/76864977-4dd35280-6862-11ea-81f8-d4ea4d3f36c4.png)
![Retroshare-logo](https://user-images.githubusercontent.com/88840/76864979-4dd35280-6862-11ea-99d5-51e8601506ce.png)
![vagrant-logo](https://user-images.githubusercontent.com/88840/76864981-4e6be900-6862-11ea-8603-7d8cd001bb23.png)

### How to solve this issue
 - Create a component

### How to reproduce the user scenario
 - Run the project locally and you will see the home page

### Tips
Reuse our existing components and don't forget about translations for text strings and update the top menu with the section links

**Comment by ceyuboglu** [comment]
Hey, I would like to help about this

**Comment by alexanmtz** [comment]
Hello @ceyuboglu, that's great! You're now assigned and you can start to work on this issue 👍

**Comment by alexanmtz** [comment]
Your changes was merged and deployed @ceyuboglu, thanks for the contribution 👍
