### ISSUE TITLE
Notify user assigned about deadline updates

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#499]
When a deadline is extended or set with a user assigned, notify the assigned user with an email:

We have already set the mail functions with an update for deadlines:
https://github.com/worknenjoy/gitpay/blob/7dbb832ee8859436b31518966a18f5a0ff5e58ea/modules/mail/deadline.js

So it should work, but for some reason, these e-mails are not working.

### Why
We need to notify assigned users about a deadline extended, so he can continue to work on that issue and we will have the reminder again when the new deadline ends.

### Level
Beginner

### Current behavior
When a deadline is extended from an issue, there's no notification 

### Expected behavior
Send an email to an assigned user when a deadline is extended

### Useful links
  - https://github.com/worknenjoy/gitpay/blob/master/modules/tasks/taskUpdate.js#L134

### How to reproduce the user scenario
 - Create an user
 - Import an issue
 - Create another user
 - Apply to solve an issue in _I'm interested_
 - Log with the first user
 - Assign user
 - Change deadline
 - An email should be sent (locally will not receive an email, but you can debug on console)

### Tips
To debug emails you will need to check if the mail function call, cause it's not easy to reproduce locally. If you can't do that, we can provide temporary development API in order to receive real mails with Sendgrid.

**Comment by khoded** [comment]
Hi alex would love to be assigned this issue

**Comment by alexanmtz** [comment]
Hey @khoded, you're now assigned to this issue 👍
