### ISSUE TITLE
Random images at home page

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#500]
We would like to load different images on our home page from developers and remote work categories.

You can follow this tutorial as reference: 
https://dev.to/desi/using-the-unsplash-api-to-display-random-images-15co

### Why
We want a more dynamic home page and this is a pretty interesting challenge

### Level
Beginner

### Current behavior
A fixed home image

### Expected behavior
For each loading we load a different image

### Useful links
  - https://dev.to/desi/using-the-unsplash-api-to-display-random-images-15co

### Tips
Check the image resolution and size to not overload our page load

**Comment by Progressandro** [comment]
Hi, I'm looking forward to start contributing to Open Source and I like very much the concept of this project.

I would like to know where exactly would these images go. Do you have any sketch or further specs?

**Comment by alexanmtz** [comment]
Hello @Progressandro, it would be awesome if you could work on this.

I think we don't need a design to this one, it's the main image at the home page, the presentational image in our main hero call. 

Is this static image that should be replaced by random images from Unsplash: https://gitpay.me/960b3d9b3ed3000f99c120121c4928f1.jpg

**Comment by Progressandro** [comment]
Great, I'll try getting this done tonight.

This will be my first contribution attempt, I'll do my best but hope you can understand if I don't nail the PR at first try :grinning: .

**Comment by alexanmtz** [comment]
I assigned you @Progressandro and we help you in whatever you need to complete, and we're glad that you starting to contribute and that you will do your first contribution with us 🙏

**Comment by alexanmtz** [comment]
Let's see how it works, great solution and thanks for contributing @Progressandro 🚀

**Comment by Progressandro** [comment]
Alright then, thanks for the assignation @alexanmtz ! :grinning: 

Would you mind if I try to solve other issues? Or there are already covered? I need real life examples for my React practices, and it would be nice if it can also help the project :smile:

**Comment by alexanmtz** [comment]
Sure @Progressandro, feel free to comment on the issue you want to challenge yourself, and I can assign you 👍
