### ISSUE TITLE
Add issue title in all email notifications templates

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#503]
We need to update all email notifications to include the issue title and not only the URL as today.

### Why
Now we're providing only the issue URL, so the user needs to click to actually know what this issue is about, so it would be good to include `title` on email templates.

### Level
Beginner

### Current behavior
On our email notifications related to tasks, we provide only the url on our notifications

### Expected behavior
We should include the title as we do it here:
https://github.com/worknenjoy/gitpay/blob/master/modules/mail/assign.js#L149

### usefull links
  - https://github.com/worknenjoy/gitpay/blob/master/modules/mail/assign.js#L149

### How to solve this issue
 - Look for all email template variables passed in our mail modules:
https://github.com/worknenjoy/gitpay/tree/master/modules/mail

### Tips
You can test emails with automated tests, by verifying that the title is being passed to the template, or you can debug with the console because the emails will not be sent locally. If you need to test locally, we can send temporary development keys for Sendgrid to be able to send emails from your local environment

**Comment by vercettizarak** [comment]
I want to work on this issue

**Comment by alexanmtz** [comment]
Hello @vercettizarak, you're now assigned 👍
