### ISSUE TITLE
Keep only one tab when add bounty or change deadline

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#504]
When we open _Add bounty_ or _Deadline_ it should keep just the current clicked opened

### Why
It gets confused when both are opened and it would be nice to close one as tabs

### Level
Beginner

### Current behavior
The two contexts open when you click in each one (See screenshot)

### Expected behavior
It should keep just one open (Add bounty or Deadline)

### Screenshot attached
<img width="1075" alt="Screenshot 2020-03-17 at 18 35 44" src="https://user-images.githubusercontent.com/88840/76884637-47eb6a80-687e-11ea-9ad3-3c617eb9e1ce.png">

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - Click in _Add bounty_ and _Deadline_

**Comment by sep2001aryan** [comment]
hello I would like to work on this issue as my first issue :)

**Comment by alexanmtz** [comment]
You're now assigned @sep2001aryan 👍
