### ISSUE TITLE
Enable apply button when interested user choose issue for learning purposes 

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#507]
When a user is interested to work on an issue, we have an option to apply for learning purposes, but now there's a bug that the button to apply is not enabled when he set to work for learning purposes

### Level
Beginner

### Current behavior
The button is not enabled when you check _For learning purposes_ when you're applying to solve an issue

### Expected behavior
The button to apply to solve that issue should be enabled when the user checks that he's applying for learning purposes

### Screenshot attached
<img width="611" alt="Screenshot_2020-02-12_at_18 10 39" src="https://user-images.githubusercontent.com/88840/77074106-9ae52f00-69f0-11ea-9acb-fc79bf4e2583.png">

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - Create another user
 - Apply to solve that issue

**Comment by Progressandro** [comment]
Please assign this one to me, already solved it :rocket: .

**Comment by alexanmtz** [comment]
Great @Progressandro , great catch, you can create now a PR with your changes 👍

**Comment by alexanmtz** [comment]
Great @Progressandro, your changes was merged and deployed. Thanks for contributing 🚀
