### ISSUE TITLE
Send message for assigned users is not working

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#508]
When a user is assigned, we have a box to send him a message, the same that open on the interested list, but for some reason, the modal to send a message is not showing. 

### Level
Beginner

### Current behavior
When clicking in _Send Message_, on the assigned message box, nothing happens

### Expected behavior
When clicking in _Send Message_, open the dialog to send message to that user, the same as the one on the interested list

### Screenshot attached
<img width="1066" alt="Screenshot_2020-02-14_at_15 46 04" src="https://user-images.githubusercontent.com/88840/77084353-25cd2600-69ff-11ea-8b9e-b1b6548b938e.png">

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - Create another user
 - Apply to solve
 - Log in with the first user
 - Assign that user
 - Try to send a message in the message box as the screenshot

**Comment by ChukwuEmekaAjah** [comment]
Okay. I would like to solve this.

**Comment by alexanmtz** [comment]
Hello @ChukwuEmekaAjah, you're now assigned and you can start to work on this issue 👍

**Comment by alexanmtz** [comment]
Fixed
