### ISSUE TITLE
Wrong email sender when send message to interested users

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#510]
When an email is sent using our message system, it should send as the current user logged not the author

### Why
When we send message to interested and assigned users, the message from seems to use the author who imported that issue to Gitpay, but users from original issues have access and can send messages, so we need to make sure that the message from is from the current user

### Level
Beginner

### Current behavior
A different user who sends the email on the e-mail to interested users and assigned

### Expected behavior
When a user sends a message to interested users, it should display the sender as the current user, not the issue author.

### How to reproduce the user scenario
- Create user
- Import issue
- Create another user
- Apply to solve the issue
- Log with the first user
- Send a message to the first user on the interested tab

### What you will need to complete this issue
You will need the Sendgrid keys to test the emails

**Comment by azdrenymeri** [comment]
Hello,
I want to work on this issue.

**Comment by alexanmtz** [comment]
Hello @azdrenymeri, you're now assigned to work on this issue 👍

**Comment by alexanmtz** [comment]
The issue was fixed and deployed, thanks @azdrenymeri to your contribution 👍

**Comment by alexanmtz** [comment]
Hello @azdrenymeri, can you contact us at hiring@gitpay.me in order to proceed with the interview for the intern position on Gitpay?
