### ISSUE TITLE
Add issue deadline to calendar

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#514]
When the assigned user receives the notification about the deadline for an issue, please provide the link to add to the user calendar.

### Why
It would be amazing if we can add the deadline to the user calendar, so this user will be aware of the deadline expected to send a solution to that issue.

### Level
Beginner

### Current behavior
When an email is sent to the assigned user, the user receives the email with the deadline date.

### Expected behavior
When an email is sent to the assigned user, the user will have the link on the email content to add that deadline to the calendar

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - Set deadline
 - Create another user
 - Apply to solve that issue
 - Log with the first user
 - Assign that user
 - The email notification should have the link to add to the calendar

### What you will need to complete this issue
You will need the development keys for Sendgrid to receive an email, that will be provided when you're assigned.

### Tips
Check the variables that we send on emails, so we need to add a new one with the link passing the event date to the link that points to the calendar.

**Comment by Faithfinder** [comment]
Hi! Please assign this to me.

**Comment by alexanmtz** [comment]
Hello @Faithfinder, you're now assigned 👍

**Comment by Faithfinder** [comment]
Hey, so are you talking about Google Calendar link? Because as far as I know there's no universal "calendar link" like there is a "mailto" one. I can also generate and attach an .ics file, but that's, obviously, not a link.
Also you've promised me keys to Sendgrid?

**Comment by alexanmtz** [comment]
Hello @Faithfinder ,
Yes, a Google calendar is enough.

I will send you the Sendgrid development API_KEYS.

**Comment by alexanmtz** [comment]
Hello @Faithfinder, can you contact us at hiring@gitpay.me in order to proceed with the interview for the intern position on Gitpay?
