### ISSUE TITLE
Unit tests for email template is failing

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#516]
We have now some unit tests on our email templates.

### Level
Beginner

### Useful links
  - https://github.com/worknenjoy/gitpay/blob/master/test/email.test.js#L10

### How to reproduce the user scenario
 - Replace `xdescribe` to `describe` to see the mail tests running

### What you will need to complete this issue
Run the tests

### Tips
xdescribe is a way to skip some unit tests

**Comment by namandangi** [comment]
I'll work on this , assign me.

**Comment by alexanmtz** [comment]
As discussed with @namandangi, we will need to do changes in `canSendMail` in constants, in order to allow mails to test Mail functions using Unit Tests, so we will need to create another issue to address this and start to remove this parameter and mock Sendgrid calls.

So once I have this issue created, we can close this one.
