### ISSUE TITLE
Duplicated user on the user interested tab

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#517]
We should have a unique interested user row on the interested tab on the task page

### Level
Beginner

### Current behavior
When you're interested to work on an issue, you can apply in _Im' interested_ and if you apply twice, you will see a duplicate entry

### Expected behavior
Users interested should be unique and rather then add a new one, it should update the current interested with the last information provided

### Screenshot attached
<img width="1080" alt="Screenshot_2019-12-02_at_11 19 04" src="https://user-images.githubusercontent.com/88840/77255968-747ef800-6c6b-11ea-9f3d-54356dc87243.png">

### How to reproduce the user scenario
- Create a user
- Import an issue
- Create another user
- Apply to solve that issue
- Apply again
- You will see two entries

**Comment by silanka007** [comment]
Good day sir. Please I would like to work on this issue.

**Comment by alexanmtz** [comment]
Hello @silanka007 , you're now assigned to work on this issue

**Comment by silanka007** [comment]
> Hello @silanka007 , you're now assigned to work on this issue

@alexanmtz thank you very much sir

**Comment by silanka007** [comment]
if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^
TypeError: OAuth2Strategy requires a clientID option

this error comes up everything I try to start up the node server.

**Comment by alexanmtz** [comment]
Hello @silanka007, I think you're missing a step in our documentation to copy the `.env.example` to `.env` in your local environment.

**Comment by silanka007** [comment]
Yeah I figured it out. I had to source the .env file. its now working!

**Comment by silanka007** [comment]
I am done resolving the issue sir. I will be sending in the pull request now.
