### ISSUE TITLE
Wrong target on Bottom navigation

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#519]
There are one / more items on bottom navigation pointing to the wrong target dialog

### Level
Beginner

### How to reproduce the user scenario
 - Go to the home page and check the bottom navigation

**Comment by nrrao** [comment]
I looked into the bottom navigation. All the links are working.
![bottom navigation](https://user-images.githubusercontent.com/25930687/79379258-a6af0d00-7f2c-11ea-86b8-ed433a6912dd.PNG)

**Comment by alexanmtz** [comment]
Hello @nrrao, all the links are working but some of the links point to the wrong target

**Comment by nrrao** [comment]
When I click on the links the content for how it works for freelancers and company is the same but the heading is appropriate. Could you give me an example of a wrong target?

**Comment by alexanmtz** [comment]
@nrrao, maybe on the interface seems right, but looking into the code to see duplicate sessions, cause all sections are unique. Look into the existing code to create the translation entries.

**Comment by alexanmtz** [comment]
Fixed 👍
