### ISSUE TITLE
NaN displaying on interested dialog when the suggested value is empty

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#520]
When the price is empty again, the confirmation checkbox retrieves NaN, it should display to the original initial value.

### Why
Motivations when solving this issue

### Level
Level required to conclude this issue

### Current behavior
current behavior

### Expected behavior
expect behavior

### usefull links
  - https://example.com

### Screenshot attached
<img width="611" alt="Screenshot 2020-03-22 at 19 18 19" src="https://user-images.githubusercontent.com/88840/77257036-1c97bf80-6c72-11ea-9e1e-bc3f9e240930.png">

### How to reproduce the user scenario

 - Create a user
 - Import an issue
 - Create another user
 - Apply to solve that issue
 - Try to suggest a price and before confirm, make it empty again

**Comment by iamNarcisse** [comment]
Hello, @alexanmtz I want to work on this issue.

**Comment by alexanmtz** [comment]
Hello @iamNarcisse, sorry for the late response, you still want to work on this?

**Comment by iamNarcisse** [comment]
Hi Alexandra,

I have worked on it already.

Should I wait till it is assigned to me before I make a PR?

**Comment by alexanmtz** [comment]
@iamNarcisse You're now assigned and you can send you PR 👍
