### ISSUE TITLE
Notify the updates from history to users interested to work in a task

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#522]
We have the history from an issue added to Gitpay, and we would like to send a mail notification to all interested users.

### Why
We want to notify interested users about all updates from an issue imported to Gitpay.

### Level
Beginner

### Current behavior
When some state from an issue changes, nothing happen.

### Expected behavior
When any update happens, we have a table that stores the change and we should send an email to interested users about that change.

### Useful links
  - https://github.com/worknenjoy/gitpay/blob/master/models/task.js#L46

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - Create another user
 - Apply to solve that issue
 - Log with the first user
 - Assign to the second user
 - Change some status (like change deadline, status) and you should receive the notification

### What you will need to complete this issue
You will need the Sendgrid keys in order to solve this issue and we will send once you're assigned.

### Tips
We already have a format to make the status change more user friendly.

**Comment by jeevansrivastava** [comment]
@alexanmtz I want work on this.

**Comment by alexanmtz** [comment]
Not a priority now, we need to get the network history updates rethinking
