### ISSUE TITLE
Assigned card on the top when add bounty is opened

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#523]
The assigned card should be displayed below the add bounty component.

### Level
Beginner

### Screenshot attached
<img width="809" alt="Screen_Shot_2019-05-27_at_6 40 00_PM" src="https://user-images.githubusercontent.com/88840/77257744-8619cd00-6c76-11ea-948a-df50848ad1ba.png">

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - Create another user
 - Apply to solve the issue
 - Log with the first user
 - Assign the second user
 - Check the assigned component and click add bounty and you will see the assigned on the top, it should be displayed below.

**Comment by sanjaypokkali** [comment]
Hi I would like to work on this issue

**Comment by alexanmtz** [comment]
Hello @sanjaypokkali, that's great, you're now assigned and you can start to work on this issue 👍

**Comment by sanjaypokkali** [comment]
Hi @alexanmtz , I am having some trouble with downloading all the dependancies and getting the project running on my local machine. Could you please list the steps to get it working. That would be greatly appreciated.

My npm version is 6.14.4

**Comment by alexanmtz** [comment]
@sanjaypokkali, have you looked into our [README?](https://github.com/worknenjoy/gitpay/blob/master/README.md)?

**Comment by sanjaypokkali** [comment]
@alexanmtz I got it working but when I try running the backend, I'm getting this error:

C:\Users\sanja\Desktop\gitpay\node_modules\passport-oauth2\lib\strategy.js:82                                             if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }                                                     ^                                                                                                                                                                                                                    TypeError: OAuth2Strategy requires a clientID option                                                                        at Strategy.OAuth2Strategy (C:\Users\sanja\Desktop\gitpay\node_modules\passport-oauth2\lib\strategy.js:82:34)           at new Strategy (C:\Users\sanja\Desktop\gitpay\node_modules\passport-google-oauth20\lib\strategy.js:52:18)              at Object.<anonymous> (C:\Users\sanja\Desktop\gitpay\config\passport.js:63:3)                                           at Module._compile (internal/modules/cjs/loader.js:959:30)                                                              at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)                                                at Module.load (internal/modules/cjs/loader.js:815:32)                                                                  at Function.Module._load (internal/modules/cjs/loader.js:727:14)                                                        at Module.require (internal/modules/cjs/loader.js:852:19)                                                               at require (internal/modules/cjs/helpers.js:74:18)                                                                      at Object.<anonymous> (C:\Users\sanja\Desktop\gitpay\server.js:10:1)                                                    at Module._compile (internal/modules/cjs/loader.js:959:30)                                                              at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)                                                at Module.load (internal/modules/cjs/loader.js:815:32)                                                                  at Function.Module._load (internal/modules/cjs/loader.js:727:14)                                                        at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)                                                     at internal/main/run_main_module.js:17:11                                                                           [nodemon] app crashed - waiting for file changes before starting...

**Comment by sanjaypokkali** [comment]
I think i require an api key to get the backend running

**Comment by alexanmtz** [comment]
this error happens because you need your `.env` file from `.env.example` as described on our documentation @sanjaypokkali

**Comment by sanjaypokkali** [comment]
I've sent an email to the email that was attached to get the api keys but I have not gotten a response yet

**Comment by alexanmtz** [comment]
You don't need any API keys to conclude this task @sanjaypokkali , you need to create accounts and assign, which no API key is required when you create an account locally on Gitpay.

**Comment by alexanmtz** [comment]
Not relevant anymore as we redesigned this page
