### ISSUE TITLE
Should confirm an account created

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#524]
When a new account is created (register with a local account, Github or Bitbucket), the user should confirm the account.

### Why
When an account is created, we need a way to confirm to increase security and avoid spams accounts.

### Level
Medium

### Current behavior
When the user Sign up, there's no confirmation to validate his account.

### Expected behavior
When the user Sign up, create the account as usual, but send an email with confirmation and the user should have an attribute like `verified: false`

### How to reproduce the user scenario
 - Create a user

**Comment by joemart** [comment]
Challenge accepted

**Comment by alexanmtz** [comment]
Hello @joemart, you're now assigned 👍

**Comment by alexanmtz** [comment]
User confirmation implemented
