### ISSUE TITLE
insecure HTTP cookies

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#526]
On our Find a bug and fix program #272, add secure flags in our HTTP cookies to improve security

### Level
Beginner

**Comment by Ayush-Vish** [comment]
@alexanmtz  I want to work on this issue , please assign it to me.

**Comment by alexanmtz** [comment]
Hello @Ayush-Vish thanks for your interest to contribute with Gitpay, I will assign this issue to you and feel free to start to work on it and send the PR when you’re done

**Comment by Ayush-Vish** [comment]
@alexanmtz  thanks for assigning me.
