### ISSUE TITLE
See on provider link should go to a new tab

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#529]
When we have a provider (Github or Bitbucket) link on the task page and task explorer, it should direct to a new tab.

### Level
Beginner

### How to reproduce the user scenario
 - Create a user
 - Import an issue

**Comment by clarencepenz** [comment]
I'm interested

**Comment by alexanmtz** [comment]
Hey @clarencepenz, you're now assigned and you can start to work on this issue 👍

**Comment by alexanmtz** [comment]
the issue was fixed @clarencepenz, thsanks for your contribution 💯

**Comment by alexanmtz** [comment]
Hello @clarencepenz, can you contact us at hiring@gitpay.me in order to proceed with the interview for the intern position on Gitpay?

**Comment by clarencepenz** [comment]
Hello Alexandre,

Yes I can. I'll do that shortly.

**Comment by clarencepenz** [comment]
Hello Alexandre,

I trust you are well.

Did you get my email regarding the interview?

Looking forward to your reply.

Warm regards,
Clarence Bakosi

**Comment by alexanmtz** [comment]
@clarencepenz you will receive a message calling for an interview 👍

**Comment by clarencepenz** [comment]
Hello Alexandre,

I trust you are well.

I haven't heard from you since after the interview.

Looking forward to your reply.

Warm regards,
Clarence Bakosi

**Comment by alexanmtz** [comment]
Hey @clarencepenz, I'm good, I hope you're well too. We will move ahead this month and we will let you know the response.

**Comment by clarencepenz** [comment]
Hello Alexandre,

I'm good too. Thanks for replying. I look forward to a positive response.

Warm regards,
Clarence Bakosi

**Comment by clarencepenz** [comment]
Hello Alexandre,

I trust you're well. I'm reaching to inform you that I can now take on the
6hrs per day instead of the 4hrs per day I originally opted for. I look
forward to a consideration and a positive response.

Warm regards,
Clarence Bakosi
