### ISSUE TITLE
Remove all email information about the assigned user on email templates

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#530]
We don't want to provide more email information on the email we send to the user when he assigns a user, as well as other email notifications.

### Why
We have now a message system, so no need to share the e-mail in the email notification body

### Level
Beginner

**Comment by jeevansrivastava** [comment]
@alexanmtz i want to work on this. But  i am first time contributor

**Comment by alexanmtz** [comment]
Hey @jeevansrivastava, that's great, you're now assigned and you can do your first contribution 👍

**Comment by jeevansrivastava** [comment]
Thanks @alexanmtz , can you briefly explain what content i have to remove . And steps to reproduce.

**Comment by alexanmtz** [comment]
Great @jeevansrivastava, it's good questions indeed.

We have email notification modules like this one: https://github.com/worknenjoy/gitpay/blob/master/modules/mail/assign.js

And they use locales files: https://github.com/worknenjoy/gitpay/blob/master/locales/en.json

We need to remove all references of the contributor e-mail when we're sending e-mail notifications.

Like this one: https://github.com/worknenjoy/gitpay/blob/master/locales/en.json#L20

To reproduce, you can please request me the keys by e-mail (apikeys@gitpay.me) or joining our [Slack Channel](https://join.slack.com/t/gitpay/shared_invite/enQtNDg4NzM2NDI5NDg4LTk1ZTlhMGJhOGJlOGJhNjgzNTJjM2QxMmNjM2M4Njk0YjllZDBiZDFjZTVlMzBiMzU0NTI3NjE2YWNhNjllOTQ)
