### ISSUE TITLE
Add Mailchimp language preference to that user and keep in sync

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#531]
When a user is created, we add this user to a Mailchimp list, so we should send the user preference of language and update when this user updates their preferences. 

### Why
When we need to send a campaign to different markets based on user preferences.

### Level
Beginner

### Useful links
  - https://mailchimp.com/developer/

### How to reproduce the user scenario
 - Create a user - should add to the MailChimp list with the right language preference
 - Update user preferences - should update that user language preference

### What you will need to complete this issue
Mailchimp keys that will be sent when you're assigned.

### Tips
Use our functional test structure to create automated tests for this.

**Comment by iamfortune** [comment]
hi, ready to do this

**Comment by alexanmtz** [comment]
Hello @iamfortune, you're now assigned and you can start to work on this issue 👍

**Comment by alexanmtz** [comment]
We will move out from Mailchimp because it's too expensive for us
