### ISSUE TITLE
Display the number of items on the task explore filter

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#533]
We want to display the number of items from a filtered list

### Why
So we have an idea of how many items we have in that collection of filters.

### Level
Beginner

### usefull links
  - https://mui.com/material-ui/react-chip/

### Screenshot attached

<img width="562" alt="Screen Shot 2024-01-03 at 8 52 07 PM" src="https://github.com/worknenjoy/gitpay/assets/88840/74a26fa1-c7e8-4301-a199-51ac62d8f522">

### Tips
Look on Material-UI how to implement the component using the chip component to display the counter:

**Comment by nikhil-sachdeva** [comment]
Can I work on this ?

**Comment by tusharkudal** [comment]
I would like to work on this issue.

**Comment by alexanmtz** [comment]
@tusharkudal you're now assigned 👍

**Comment by Sid-80** [comment]
I would like to contribute to the project. Assign me this issue.

**Comment by alexanmtz** [comment]
Great @Sid-80 , you're assigned now 🙏

**Comment by Sid-80** [comment]
There is issue while cloning the repo

**Comment by alexanmtz** [comment]
Hey @Sid-80 , can you share the issue you're having?

**Comment by jaymehta002** [comment]
@alexanmtz  Assign me this issue.

**Comment by alexanmtz** [comment]
Hey @jaymehta002 you're assigned now, and I will check why the project is down.

**Comment by jaymehta002** [comment]
can you just let me have some reference to the file. It is just a minor fix

**Comment by alexanmtz** [comment]
Hey @jaymehta002 , the platform is open again and you can see the Issue explorer here: https://gitpay.me/#/tasks/open

**Comment by jaymehta002** [comment]
i have raised a PR. Since i cannot run this on local machine. Give it a review. 
just added a count filter

**Comment by alexanmtz** [comment]
Hey @jaymehta002 I saw your PR #1050 , but you should be able to run locally to test, and your solution is incomplete, because your count variable is passed but not in the caller, so you should run locally to see by yourself the result

**Comment by Sajid-tech** [comment]
If the issue is still open , I would like to contribute, ASSIGN me

**Comment by alexanmtz** [comment]
yeah @Sajid-tech, it is still open and you can work on this and send a PR with the feature 👍

**Comment by alexanmtz** [comment]
@Sajid-tech are you working on it?

**Comment by alexanmtz** [comment]
Concluded by @RemyaManoharan, thanks for the contribution 💯
