### ISSUE TITLE
Welcome user

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#534]
A wizard when the user creates an account 

### Why
A warm welcome to our user and basic instructions

### Level
Beginner

### Screenshot attached
![Mobile3](https://user-images.githubusercontent.com/88840/77318507-78fbed00-6d0d-11ea-9f40-945f2e4a8cd3.png)
![Mobile2](https://user-images.githubusercontent.com/88840/77318514-7b5e4700-6d0d-11ea-933d-c805f662229e.png)
![Mobile1](https://user-images.githubusercontent.com/88840/77318518-7c8f7400-6d0d-11ea-8842-8ce282183a99.png)
![welcome-main-screen](https://user-images.githubusercontent.com/88840/77318519-7dc0a100-6d0d-11ea-97bf-9afff71a9cb2.png)

### Assets
![Group 2](https://user-images.githubusercontent.com/88840/77318648-b3fe2080-6d0d-11ea-83d0-c248e91365cb.png)
![Group 4](https://user-images.githubusercontent.com/88840/77318657-b5c7e400-6d0d-11ea-818a-b64ff6269248.png)
![Group 5](https://user-images.githubusercontent.com/88840/77318660-b6f91100-6d0d-11ea-8aa0-4b6cd9003a48.png)

### How to reproduce the user scenario
 - Create a user
 - A first-time welcome should display the wizard

### Tips
Look for #266

**Comment by alexanmtz** [comment]
Hello @sonny-maan, you're now assigned and you can start to work on this issue 👍

**Comment by alexanmtz** [comment]
@sonny-maan, you were unassigned cause we hadn't any response from you

**Comment by Simran-Chaudhary** [comment]
Hey, I'd like to work on it. Please assign if it's still open

**Comment by alexanmtz** [comment]
You're now assigned @Simran-Chaudhary and you can start to work on this 👍

**Comment by Simran-Chaudhary** [comment]
Thanks. Raised a pr, please review https://github.com/worknenjoy/gitpay/pull/712
