### ISSUE TITLE
Change account settings

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#535]
A new item on a user account to change their account settings. The menu have an item _Settings_ and the user will be able to connect from Github, Bitbucket or local account and change settings.

### Why
We need a way to change the initial settings from that user

### Level
Beginner

### Screenshot attached
![change-account](https://user-images.githubusercontent.com/88840/77318828-093a3200-6d0e-11ea-9d5f-db20742fff35.png)

### How to reproduce the user scenario
 - Create an account. We should have an account setting item on the user account page menu

### What you will need to complete this issue
You will need the Github and Bitbucket development keys to log and we will send once you're assigned.

**Comment by namandangi** [comment]
I'll take this up , assign me @alexanmtz

**Comment by alexanmtz** [comment]
Yes, you're now assigned @namandangi

**Comment by alexanmtz** [comment]
@namandangi tip: you can use the same approach as #666 to have a route to this page but don't worry about include in any menu for now.
