### ISSUE TITLE
No bounty added label

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#536]
We need to display "No bounty added" instead of $0 on the task page and task explorer

### Why
We want a more clear way to communicate about the state of the funds for that issue

### Level
Beginner

### Screenshot attached
![Desktop Copy](https://user-images.githubusercontent.com/88840/77323839-2bd04900-6d16-11ea-89c2-f220c2c2e231.png)
![Desktop](https://user-images.githubusercontent.com/88840/77323855-2f63d000-6d16-11ea-8094-6bfc36e057f7.png)

### How to reproduce the user scenario
- Create a user
- Import an issue

**Comment by qiweiii** [comment]
@alexanmtz  Could i take this one? I think i can do this.

**Comment by alexanmtz** [comment]
Yes @qiweiii , it is now assigned to you

**Comment by qiweiii** [comment]
Hi @alexanmtz I created a PR #574 for this, could you please take a look?

**Comment by alexanmtz** [comment]
Merged and deployed 🚀 , thanks for the great contribution @qiweiii 🎉
