### ISSUE TITLE
Gitpay team

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#537]
A new page (should be included in the top menu "Team"), with a list of team members from the core. The data can be a simple JSON with name, role, description, picture URL, website, and Github (or Bitbucket) profile.

A component to notify someone who wants to join the team. The join action should send an email to our notifications mail (in a constants file) with the content:

```
The user with the email {{email}} wants to join to Gitpay core team
```

### Why
We have a core team and we need to display who is working for Gitpay.

### Screenshot attached
![gitpay-team](https://user-images.githubusercontent.com/88840/77324510-28898d00-6d17-11ea-8d4c-acc18875b6ee.png)

### Assets
![Group2](https://user-images.githubusercontent.com/88840/77333987-7eb0fd00-6d24-11ea-9704-d344a53ea9a9.png)

**Comment by harshlakhanpal** [comment]
Hello Sir ,I'd like to work on this issue.

**Comment by alexanmtz** [comment]
Hello @harshlakhanpal, you're now assigned to this issue and you can start to work on it 👍

**Comment by alexanmtz** [comment]
No response from you @harshlakhanpal , so you were unassigned to this.

**Comment by keshavg2** [comment]
Hi @alexanmtz I'd like to work on this issue?

**Comment by alexanmtz** [comment]
Hey @keshavg2, great, you're now assigned to this issue 👍 

We have a card components for members used in gitpay.me/#/recruitment and you can use the same component

**Comment by keshavg2** [comment]
Thanks @alexanmtz

**Comment by keshavg2** [comment]
Hi @alexanmtz can You please tell me where I should include in the Top Menu "Team". If you don't understand the question then feel free to ask me.

**Comment by alexanmtz** [comment]
@keshavg2, for now, it's a route to this team page, and you don't need to include on the menu right now.

**Comment by alexanmtz** [comment]
Hey @keshavg2, any progress on this?

**Comment by keshavg2** [comment]
Hi @alexanmtz I'm working on it to solve this issue.

**Comment by alexanmtz** [comment]
Hello @keshavg2, any update on this? We're looking forward to seeing this in action!

**Comment by alexanmtz** [comment]
Hey @keshavg2 there's no update in 15 days, so I will remove your assignment and leave this issue available again

**Comment by salonigoyal2309** [comment]
hey , i would love to work on this issue :)

**Comment by alexanmtz** [comment]
Hey @salonigoyal2309, please! You are now assigned and you can start to work on it.

Please follow the discussions here that we have, and that this component already exists in the team section.

So this issue is to make this component more generic and use for a Team page and keep it on the Recruitment page
<img width="979" alt="Screen Shot 2020-09-17 at 11 26 42 PM" src="https://user-images.githubusercontent.com/88840/93530087-4427c600-f93d-11ea-872e-30c33bfa2f55.png">

**Comment by salonigoyal2309** [comment]
hey @alexanmtz  i was working on this issue and i was wondering what library i should use for sending emails ? I am little new to open source and your suggestion would help me a lot.

**Comment by alexanmtz** [comment]
Hello @salonigoyal2309, you will be able to see in the terminal of the node server the output of the email when is sent.

Let me know if you have any other questions, and happy coding 💻
