### ISSUE TITLE
Stats page

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#538]
A status page as the screenshot, with relevant data about the platform. It should be on the path `/stats`

### Why
We want to have our stats to our users and to follow the community numbers.

### Level
Advanced

### Screenshot attached
![stats-page](https://user-images.githubusercontent.com/88840/77335127-08ad9580-6d26-11ea-84a8-33920c93e456.png)

### Assets
![Group-graph](https://user-images.githubusercontent.com/88840/77335951-2a5b4c80-6d27-11ea-9d1f-d45216411332.png)
![ic_products2](https://user-images.githubusercontent.com/88840/77335956-2af3e300-6d27-11ea-948b-575a826a42ef.png)
![ic_products](https://user-images.githubusercontent.com/88840/77335957-2af3e300-6d27-11ea-99f5-c6721ff782e9.png)
![icon-1](https://user-images.githubusercontent.com/88840/77335958-2b8c7980-6d27-11ea-9100-f1e50ffaed55.png)

### Tips
- I did a script https://github.com/worknenjoy/gitpay/blob/master/reports.js which lists the bounties by month, just to have a good reference.
- Pay attention to how to retrieve some of this data. To get the labels, we need to call Github, so this will be added in another ticket, and you can leave it for now, and show only one tab, but in the way that is there, with no data, and once we have the data, it can be added.

**Comment by sep2001aryan** [comment]
hello ... i would like to work on it

**Comment by alexanmtz** [comment]
Hey @sep2001aryan, this is a really challenging one. You're now assigned and you can start to work on it. Let me know if you have any questions 👍

**Comment by sep2001aryan** [comment]
yes sure

**Comment by alexanmtz** [comment]
@sep2001aryan, thanks for the great contribution.

I just realized that the bottom is missing, could you send a PR with the generic bottom bar?

**Comment by sep2001aryan** [comment]
Yeah sure . But can you send the design of what bottom look like .... In the design you sent i think there was no bottom 😬

**Comment by alexanmtz** [comment]
@sep2001aryan it's the same bottom of all pages.  You can see the component here:
https://github.com/worknenjoy/gitpay/blob/master/frontend/src/components/bottom/bottom.js

**Comment by sep2001aryan** [comment]
Issue will be solved by night 😁
