### ISSUE TITLE
Hire and work landing page

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#539]
Our landing page and new page to start our tool for hiring. This page should be a new route like `/recruitment`

### Why
As part of our strategy, we will start to provide a way to connect contributors to companies

### Level
Medium

### Screenshot attached
![Gitpay landing page hire - Desktop HD](https://user-images.githubusercontent.com/88840/77336979-92f6f900-6d28-11ea-8e10-63ae4ccba229.png)

### Assets
![asset-landing-page](https://user-images.githubusercontent.com/88840/77336986-95595300-6d28-11ea-8a9f-780dd8476586.png)

**Comment by Shawn-Noruzi** [comment]
Hi! I'm ready to work on this. Please Assign it to me :)
Thank you!

**Comment by alexanmtz** [comment]
Hello @Shawn-Noruzi, that's great, you're now assigned and you can start to work on this issue 👍

**Comment by Shawn-Noruzi** [comment]
Hey! 

Went to do a pull request and got hit with no permissions @alexanmtz  

I fell ill 2 days ago so slowed me down a bit unfortunately

**Comment by Shawn-Noruzi** [comment]
I got the the page made with layout + responsiveness + styling and looks like the image above. 

There's some functionality missing for the buttons but I can do that tonight easily

**Comment by alexanmtz** [comment]
Hello @Shawn-Noruzi, you need to create a fork and push for your branch, then you create a PR from there. In your cause, that you already cloned, you can add other remote:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork

Let me know if you need any help

**Comment by alexanmtz** [comment]
@Shawn-Noruzi, and that's great that you could implement the screen, don't worry about these buttons, for now, is just a landing page and you don't need to worry about the links

**Comment by Shawn-Noruzi** [comment]
Gotchya - Thank you!

I pushed it to the fork. 

https://github.com/Shawn-Noruzi/gitpay/commit/ae4f348c3e65d38cc8ad5d522f0c810621aa82e0

**Comment by Shawn-Noruzi** [comment]
Its pushed to worknenjoy:master but I dont want that -> I think I should be pushing it to a branch instead

Shawn-Noruzi wants to merge 2 commits into **worknenjoy:master** from Shawn-Noruzi:master

How do I proceed?

**Comment by Shawn-Noruzi** [comment]
npm run dev for front end works  on my end - sites visible and works. 
![gitsite](https://user-images.githubusercontent.com/25312057/80185615-7b2dc180-85c1-11ea-9d40-87a89c14c409.PNG)



But the build-all check fails on pull request - any advice on how to proceed?
