### ISSUE TITLE
A new user profile Card

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#540]
A better way to highlight the user profile

### Why
A good way to have an overview about the activities on Gitpay

### Level
Beginner

### Screenshot attached
![user-profile-card](https://user-images.githubusercontent.com/88840/77346848-2f27fc80-6d37-11ea-9ca9-9a5078112c4c.png)

### How to reproduce the user scenario
 - Create a user
 - You will be redirected to profile page with a user card component

**Comment by mdfaizan7** [comment]
Can I take this issue?

**Comment by alexanmtz** [comment]
Yes @mdfaizan7, you're now assigned 👍

**Comment by alexanmtz** [comment]
Hello @mdfaizan7, since we didn't get any response from you, you will be unassigned from this issue.
