### ISSUE TITLE
Add another avatar with the author listed on task page

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#541]
We need to display who is the original author (from Github or Bitbucket) and who created on Gitpay, so we will add another avatar along with the author currently listed. If it is the same, just list one author's avatar as we have today.

So the labels would be _author from provider_, where the provider is Github or Bitbucket, and _Imported by_ with the user who imported the issue to Gitpay

### Why
We need to know who created the issue on Github, and who imported to Gitpay.

### Level
Beginner

### Useful links
  - https://material-ui.com/components/avatars/

### Screenshot attached
<img width="918" alt="Screenshot 2020-03-23 at 18 58 01" src="https://user-images.githubusercontent.com/88840/77347564-53380d80-6d38-11ea-9452-7d2d4175983a.png">

### How to reproduce the user scenario
 - Create a user
 - Import an issue from a different author
 - You need to display two avatars, one of the original author and another with your user

**Comment by mani-developer** [comment]
I am interested to work on this issue

**Comment by alexanmtz** [comment]
You're now assigned @mani-developer 👍

**Comment by mani-developer** [comment]
great. thanks @alexanmtz

**Comment by alexanmtz** [comment]
Hello @mani-developer, you're right, there's was some issues after I tested, you actually was retrieving the current user, not the task creator, so please check my latest commit with the fix:
https://github.com/worknenjoy/gitpay/commit/1e4c28b0696fda253b1ee394b4054e4f4e7f6709

**Comment by mani-developer** [comment]
@alexanmtz  thanks for the details.  Will go through the changes and try to understand.  Happy to see my changes on the website :)

**Comment by alexanmtz** [comment]
Great @mani-developer, yeah, that's the idea, while doing challenges, to have real contributions from your end 👍 

I think we will close this for now and wait for the next steps 🙏

**Comment by mani-developer** [comment]
Sure.. Looking forward @alexanmtz  🙏

**Comment by alexanmtz** [comment]
Hello @mani-developer, can you contact us at hiring@gitpay.me in order to proceed to the interview for the intern position on Gitpay?

**Comment by springsai** [comment]
@alexanmtz  that's good to know.  Sure i will get in touch on the given email address.

**Comment by mani-developer** [comment]
@alexanmtz  that's good to know.  Sure i will get in touch on the given email address. thank you.
