### ISSUE TITLE
Provide a survey link to users who concluded some issue

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#542]
When a bounty is sent to this user and the issue is finished and paid, send a survey link to get user feedback. This notification should be sent 5 days after he concluded the issue.

The email would have the following message:
Subject: Please let us know your experience to work on this issue
Content:
```
Please respond to a <a href="{{url}}">quick survey</a> about your experience with Gitpay.
```

### Why
We want to have user feedback when an issue is concluded.

### Level
Beginner

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - Create another user
 - Apply to solve the issue
 - Log with the first user
 - Assign this user
 - Change the status to Finished
 - The user assigned should receive the email to respond to a survey.

### What you will need to conclude this issue
We need to provide the development keys for Sendgrid, in order to test the e-mail notifications.

### Tips
You can use any URL now, you don't need to worry about the survey URL right now.

**Comment by DewaldMar** [comment]
I would like this issue can you please assign the issue to me

**Comment by alexanmtz** [comment]
Great @DewaldMar, you're now assigned and you can start to work on this issue 👍
