### ISSUE TITLE
Script to show orphan accounts on Stripe with users registered on Gitpay

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#543]
We want a script that we execute in order to have the status from Stripe accounts created from Gitpay.

This script should check for each user if there's an email when checking the Stripe account information. So you should try to get that account with email, and then the script should output for each user as the example:

```
Email: sample@user.com
Found on stripe: 1
account_id on Stripe: xxx
account_id for this User: xxx
county: US
```

The script can be a new js file called `scripts.js` on the root directory

### Why
After Stripe updated their API's, we have an issue when one account is activated, it returns an error 500 but the account is created on their side and becomes orphan, without the reference to that account created

### Level
Beginner

### Useful links
  - https://stripe.com/docs/api

### How to solve this issue
 - You should create the script
 - Create automated tests mocking stripe API to show that your script will work

### What you will need to complete this issue
You should be able to test mocking Stripe in order to test the script.

### Tips
Look into Stripe API and mock the return.

**Comment by Hardik500** [comment]
I want to work on this issue.

**Comment by alexanmtz** [comment]
Hello @Hardik500, that's great, you're now assigned to work on this issue 👍

**Comment by Hardik500** [comment]
Hey @alexanmtz, I was trying to setup the project, and I noticed that there is already a script.js file in the root directory. So do I have to add anything in it or what should I do?

**Comment by alexanmtz** [comment]
Hello @Hardik500, you should add a new method in this script.js file

**Comment by f3ve** [comment]
Does this still need to be implemented?

**Comment by alexanmtz** [comment]
Yeah @f3ve, we implement a part of that at:
https://github.com/worknenjoy/gitpay/blob/master/scripts.js#L19

So we can close this one for now
