### ISSUE TITLE
Start to count the deadline when a user is assigned

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#545]
When a user is assigned, we start to count the deadline defined

### Why
We need to have the deadline starting from where a user was assigned

### Level
Beginner

### Current behavior
When a deadline is set, we start to count from the created date to count

### Expected behavior
When a deadline is set, start counting when a user is assigned

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - Set deadline
 - Create another user
 - Apply to work on that issue
 - Log with the first user
 - Assign that user
 - The deadline countdown

### Tips
Check on the platform where the deadline is displayed and when the notification is sent

**Comment by MelvinManni** [comment]
I will like to work on this issue

**Comment by alexanmtz** [comment]
Hello @MelvinManni, you're now assigned and you can start to work on this issue 👍
