### ISSUE TITLE
Display a loading state when the main page is loading

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#546]
Display a central loading when the page is loading

### Why
Feedback to have a perception that we're loading

### Level
Beginner

### Current behavior
A blank page when is loading

### Expected behavior
A loading bar before the page loads 

### Useful links
  - https://material-ui.com/components/progress/

### How to reproduce the user scenario
 - Open the home page

**Comment by etfaghaoubeid** [comment]
Hello ,I will fix this issue

**Comment by alexanmtz** [comment]
Hello @etfaghaoubeid , you're now assigned, let me know if you need any help or if you have any questions 👍

**Comment by etfaghaoubeid** [comment]
Hello , i have made a Pull request (set up  a spinner )

**Comment by alexanmtz** [comment]
Hello @etfaghaoubeid, your pull request was merged and deployed 🚀, thanks for the great contribution 👍
