### ISSUE TITLE
Display other currencies on transfer notification

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#548]
When we send notification about the transfer, we need to support all currencies

### Why
We need to handle the currency when sending this confirmation to our users.

### Level
Beginner

### Screenshot attached
![image jpeg](https://user-images.githubusercontent.com/88840/77357514-98643b80-6d48-11ea-9786-486f59f503ee.jpg)

### How to reproduce the user scenario
 - Create a user

### What you will need to complete this issue
You will need the Sendgrid development keys that we will provide once you're assigned.

**Comment by namandangi** [comment]
Hey! I would like to work on this issue

**Comment by alexanmtz** [comment]
Hello @namandangi, you're now assigned and you can start to work on this issue 👍
