### ISSUE TITLE
Display friendly dates on mail notifications

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#549]
We have some raw dates as the screenshot and we want to display friendly dates.

### Screenshot attached
![image jpeg](https://user-images.githubusercontent.com/88840/77357514-98643b80-6d48-11ea-9786-486f59f503ee.jpg)

### What you will need to complete this issue
You don't need to 

### Tips
You can use automated tests to verify if the date passed is in the way you expect.

**Comment by adamash99** [comment]
I want to work on this issue.

**Comment by alexanmtz** [comment]
Hello @adamash99, you're now assigned and you can start to work on this issue 👍

**Comment by alexanmtz** [comment]
No updated from you @adamash99 so you were unassigned. Let me know if you want to work on this to be assigned again 🙏

**Comment by KenjxJJ** [comment]
Claiming this issue.
