### ISSUE TITLE
List issue status - public or private

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#552]
List and record the issue status (public or private) on the task page and if it is a bounty.

The part to display if this issue is a bounty is just listed static, cause we just have now bounties.

### Why
We have public and private issues, so we should display the current status.

### Level
Beginner

### Screenshot attached
<img width="496" alt="Screenshot 2020-03-23 at 21 32 39" src="https://user-images.githubusercontent.com/88840/77360664-0f500300-6d4e-11ea-9954-a6b8a16d4b86.png">

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - The status should be displayed as the screenshot

**Comment by ShubhamCanMakeCommit** [comment]
It would be great if you could assign this to me.

**Comment by alexanmtz** [comment]
Good to see you again here @ShubhamCanMakeCommit, so you're now assigned and you can start to work on it 👍

**Comment by ShubhamCanMakeCommit** [comment]
Thanks. I have just one question. 
Can you advise me on how to approach this problem. How can I know that a issue is public or private? eg. I can use `this.props.task.data.status` to know the status or `task.data.deadline` to know the deadline like we do it in [task.js](https://github.com/worknenjoy/gitpay/blob/master/frontend/src/components/task/task.js#L1027)

**Comment by ShubhamCanMakeCommit** [comment]
Here is my [code diff](https://github.com/worknenjoy/gitpay/compare/master...ShubhamCanMakeCommit:feat/public-private-status#diff-29a9c3eb704a8af119ba3b38d8f75ddeR1078)
I just need to pass the write properties.
It looks like this on localhost for above.
![screen](https://user-images.githubusercontent.com/52590791/78329363-20dfa900-759f-11ea-98be-d5f975135632.png)

**Comment by alexanmtz** [comment]
Hello @ShubhamCanMakeCommit, great progress 🎉 

So, for now, you should keep static as you did, since all tasks are public and are a bounty until we define in the model these properties, so you can keep these properties as default. But please move this into a separate component, cause the task component is huge, and no shadow on this component.

**Comment by ShubhamCanMakeCommit** [comment]
Thanks. I have made the required changes.
