### ISSUE TITLE
Add react-native to preferences

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#553]
We have a preference table and some topics, and we need to add `react-native` as an option on preferences. 

### Why
We want to know users who work with React Native

### Level
Beginner

### How to reproduce the user scenario
 - Create a user
 - Go to preferences

**Comment by sep2001aryan** [comment]
Hello, I would like to work on this issue :)

**Comment by alexanmtz** [comment]
Hello @sep2001aryan, you're assigned!
