### ISSUE TITLE
Sync labels

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#554]
Sync labels between Gitpay and Github.

### Why
We will process some information from labels, and we don't want to make unnecessary requests to Github to obtain labels.

### Level
Beginner

### Useful links
  - https://developer.github.com/v3/issues/labels/

### Tips
Maybe webhooks will be the best solution.

**Comment by Adekoreday** [comment]
@alexanmtz will like to work on this task

**Comment by alexanmtz** [comment]
Hello @Adekoreday, how do you think about the steps involved to solve this issue?

**Comment by Adekoreday** [comment]
okay @alexanmtz.

My approach to solving the problem is to configure the GitHub webhook for Gitpay repository to send details of any labels created, edited, or deleted to an endpoint in the application.

I went through the code base and saw there exist a webhook endpoint that handles the following label `gitpay`(build a task) and `notify`(this update a task).

I think for this task we might want to extend such functionality for other labels types.

I think i might need more clarification on all types of label our app should handle for now, and how we should respond to each.

**Comment by alexanmtz** [comment]
Great @Adekoreday, I think it's a good way, the webhook is triggered by our Github App: 
https://github.com/worknenjoy/gitpay-github-app

And these labels are to take some action when we define a label, and we can use it considering that it continues to work on these labels, and in the same event we update a `labels `table, it depends to create a new table to store labels on Gitpay

**Comment by Adekoreday** [comment]
Nice @alexanmtz...

 from my understanding of your comment, the task will involve

- [ ]  create a label table
- [ ] update the gitpay-github-app to allow our webhook endpoints to be called on all issues.label
- [ ] if any of the labels does not exist persist them in the labels table.
- [ ] if any the label is type `gitpay` or `notify` ensure it continues with it's normal flow.
- [ ] create logic to add action to some chosen label types for now

The above is subject to review, kindly remove or add where appropriate

**Comment by alexanmtz** [comment]
Yes @Adekoreday, I think that's a good approach, you're now assigned 👍

**Comment by Adekoreday** [comment]
Alright thanks will proceed accordingly

**Comment by khoded** [comment]
Hi @alexanmtz @Adekoreday I'm currently testing my PR for issue #558  and i noticed the following.
- when an issue from github is created with labels, the labels are only shown directly from the webhook when you call the endpoint of taskFetch.js endpoint i.e fetch a single task
- When you call taskSearch.js i.e fetch all tasks,the labels for each task  aren't fetched  from the webhook and the models.Label return an empty array even for an issue with labels attached to it. see screenshot of an issue with an attached label return empty.


I believe this PR  has been merged but I need to know why labels still return empty even when they have labels attached on github

![Screenshot from 2020-06-13 13-13-11](https://user-images.githubusercontent.com/29544341/84568680-f8cbad80-ad78-11ea-8921-e33a2b65fcfc.png)

**Comment by alexanmtz** [comment]
@khoded how you're saving labels? And have you ran `npm run migrate` and `npm run migrate-test`?

**Comment by khoded** [comment]
At the moment I only created a task from a real issue on GitHub, I followed the steps but I don't think my labels are saved. 

Yes I have ran the scripts npm run migrate and npm run migrate-test.

**Comment by alexanmtz** [comment]
@khoded I think you need to add manually in this case, cause this labels sync just will work in production, so you can use the models to save sample labels

**Comment by alexanmtz** [comment]
@khoded and you don't need to add in production test issues to test this.

**Comment by khoded** [comment]
Alright then.
