### ISSUE TITLE
Open for jobs checkbox

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#557]
Add a checkbox and an attribute on the User model which record if the user is open for job opportunities

### Why
Users with this option activated will have a chance to receive job proposals from their contribution

### Level
Beginner

### How to reproduce the user scenario
 - Create a user
 - Go to user preferences

**Comment by nikhil-sachdeva** [comment]
I would like to work on this issue.
Further clarifications on implementation details : 
1.Will the implementation be similar to _receive notifications_  feature. (A checkbox to be used instead of a toggle button)
2. What would be the default value for the user.

**Comment by alexanmtz** [comment]
Hello @nikhil-sachdeva, thanks for the update, you're now assigned and about your questions:
1. Yes, it will be similar
2. The default value will be unchecked

Let me know if you have any further questions
