### ISSUE TITLE
Send weekly task with the label "Weekly digest"

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#559]
When setting a label "Weekly Digest", add this issue as part of a special weekly digest.

### Why
When we want to highlight issues we can add to a weekly digest

### Level
Medium

**Comment by khoded** [comment]
Hi alex, i believe my solution to issue #558 can help solve this issue would love to be assigned this issue too

**Comment by alexanmtz** [comment]
Great @khoded, you're now assigned 👍
