### ISSUE TITLE
Price offer on Github labels

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#562]
When an issue from Github imported to Gitpay and a bounty is added, for example, the following format: `price: 10USD` on the labels, and comment on this issue:

`A bounty of 10USD was added to this issue. See task on Gitpay: {{url}}`

### Why
A way to set on Github the actions did on Gitpay.

### Level
Medium

### Screenshot attached
![pageshot_of__Git_sever_deploy_Issue_38_tapaswenipathak_Internship-project-tasks__@_2019-06-03-1941_55](https://user-images.githubusercontent.com/88840/77419669-16682700-6dc9-11ea-8b2e-fea01a369732.png)

**Comment by arrudaricardo** [comment]
can I work on that?

**Comment by alexanmtz** [comment]
Hello @arrudaricardo, yes, but I'm afraid we will need to create a Github bot, how you think to implement this?

We have a Github app but It requires to install, so this would just work for repositories with Gitpay App installed.

Maybe with Github Actions, this would be possible, so let me know your thoughts.

**Comment by arrudaricardo** [comment]
Hey @alexanmtz, I was thinking to use the Oauth token from the private repo gitpay feature that is already implemented and make a API call at: https://developer.github.com/v3/issues/#create-an-issue
The restrictions would be that only the owner can give authorization. In this scenario we could ask authorization to the owner to post the issue by email

**Comment by alexanmtz** [comment]
Hey @arrudaricardo, it's a good approach. But just to make it clear, we will need to make a call to comment on the issue, because the issue was imported on Gitpay and it is already created on Gitpay.

And with this approach, the user would be the author of the comment.

There's a way of doing it using Github bots, so our bot would comment without asking user authorization, the cause is our user doing the comment. Let's take a look at this approach.

**Comment by arrudaricardo** [comment]
@alexanmtz, I understand, a bot would be a good call than. I can work on that than, witch github account should we use for the bot? same as the repo or a specific one for the bot?

**Comment by alexanmtz** [comment]
Great @arrudaricardo, let's proceed with that, and we have this user that we will personal tokens to authenticate, so the GitpayBot will comment. I will send you the development tokens by email.

So you're assigned to work on this 👍
