### ISSUE TITLE
Newsletter about first timers only

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#563]
A Cronjob to send a weekly newsletter with issues to Get started. The job should get all issues with the label "first-timers-only".

### Why
A way to offer simple issues so the user can start to contribute with Gitpay

### Level
Beginner

**Comment by qiweiii** [comment]
@alexanmtz I tried to implement this, please see my PR.

**Comment by qiweiii** [comment]
@alexanmtz I tried to make a PR(#573) for this issue, I added the cron job and its test case. 
I also added a mail task for it but didn't create the mail test, because i don't know what to add in locales for mail mesages.
