### ISSUE TITLE
Accept work feature to approve the start of the work

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#564]
We should have the status of an offer to track the start of work and complete that offer.

The user should receive the following email:
Subject: You were accepted to work on an issue on Gitpay
Content:
```
Hello {{name}},

You're interested to work in the issue {{title}} - {{url}} on Gitpay. To start your work, please accept or reject this proposal.

Accept - Reject
```

When the proposal is accepted, we should send the confirmation email as we have today, when rejected, we have the following notification:

Subject: The user interested to work in an issue on Gitpay rejected the assignment
Content:
```
The assignment of an issue {{title}} - {{url}} was rejected by the user interested.

The reason was: {{message}}
```

When the proposal is rejected, it goes to a page with a reason as we have when we unassign a user.

### Why
We need a step when the user is assigned, that ask that user confirmation about the start of work on that issue.

### Level
Medium

### How to reproduce the user scenario
 - Create a user
 - Import a new issue
 - Create another user
 - Apply to work on an issue
 - Log with the first user
 - Choose the user you created to start to work
 - The notification should be sent

### What you will need to complete this issue
You will need the Sendgrid keys and we will provide once you assigned

**Comment by arrudaricardo** [comment]
I can work on that, it is open in gitpay?

**Comment by arrudaricardo** [comment]
can I work on that?

**Comment by alexanmtz** [comment]
Hello @arrudaricardo, it would be great, and this one is very challenging. You're now assigned to this issue 👍
