### ISSUE TITLE
Save preferences on check

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#566]
Now we need to press save on user preferences to save, and we want to save listening change events, so when a checkbox is checked/uncheck, save these preferences.

### Why
We want to save this information once the user change.

### Level
Beginner

### How to reproduce the user scenario
 - Create a user
 - Go to preferences

**Comment by arrudaricardo** [comment]
I can work on that, it is open in gitpay?

**Comment by alexanmtz** [comment]
@arrudaricardo, It's not open on Gitpay, this is an open-source contribution issue, thanks for the PR

**Comment by alexanmtz** [comment]
Merged and deployed @arrudaricardo , thanks for the great contribution 🚀
