### ISSUE TITLE
Let users interested know if that task is already with someone assigned

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#567]
If someone show interest in an issue already assigned, let the user know.

We should send the following notification:
Subject: The issue that you're interested on Gitpay is already assigned
```
Hello {{name}},

The issue {{title}} - {{url}} is already assigned, but we let you know if it becomes available again.
```

### Why
We want to notify users to be aware that that issue is already assigned.

### Level
Beginner

### How to reproduce the user scenario
 - Create a user
 - Import an issue to Gitpay
 - Create another user
 - Apply to work on the issue created
 - Log with the first user
 - Assign this user
 - Create another user
 - Apply to work in the issue already assigned
 - The notification should be sent to the third user

### What you will need to complete this issue
You will need Sendgrid keys to test emails that we will send once you're assigned

**Comment by arrudaricardo** [comment]
I can work on that, it is open in gitpay?

**Comment by azie-ginanjar** [comment]
Hi, Could I take this task?

**Comment by alexanmtz** [comment]
Hello @azie-ginanjar, you're now assigned 👍

**Comment by azie-ginanjar** [comment]
Hello @alexanmtz, Thanks! :)
