### ISSUE TITLE
Ask feedback to contributors after payment

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#568]
Send a notification with a link to a Survey to users 5 days after he had received the notification about the transfer of the funds.

The e-mail has the following format:

Subject: How was the payment from Gitpay
Content:
```
Hello {{name}},

We have a transfer of {{value}} to your account from an issue you solved on Gitpay: {{title}} - {{url}}

Please let us know how was the experience by answering this survey:
{{surveyLink}}
```

### Why
We want to follow up to know that this user received the bounty

### Level
Beginner

### Useful links
  - https://github.com/worknenjoy/gitpay/blob/master/modules/app/controllers/webhook.js

### What you will need to complete this issue
You need to use functional tests in order to validate, cause it's hard to test webhooks.

### Tips
Don't worry about the link, send an example link as variable, and we will change when we merge your request.

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tooltip Language Issue (See Screenshot)](https://trello.com/c/2vM1Wgme/49-tooltip-language-issue-see-screenshot)

**Comment by hgupta2363** [comment]
I am interested  in this task

**Comment by alexanmtz** [comment]
Great @hgupta2363, you're now assigned and you can start to work on this 👍
