### ISSUE TITLE
Add translation to tooltips from provider

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#584]
Add a translation string for the current tooltip:
https://github.com/worknenjoy/gitpay/blob/master/frontend/src/components/task/task-table.js#L251

### Useful links
  - https://github.com/formatjs/react-intl

### Screenshot attached
![Screen_Shot_2020-04-01_at_1 41 31_PM](https://user-images.githubusercontent.com/88840/78173921-bf152700-7458-11ea-87d8-788fc8c9000e.png)

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tooltip Language Issue (See Screenshot)](https://trello.com/c/2vM1Wgme/49-tooltip-language-issue-see-screenshot)

**Comment by sachin-duhan26** [comment]
I'm interested in this issue..

**Comment by alexanmtz** [comment]
Hello @sachin-duhan26, you're now assigned and you can start to work on this issue 👍

**Comment by alexanmtz** [comment]
Hey @sachin-duhan26, are you still working on this?

**Comment by alexanmtz** [comment]
You were removed @sachin-duhan26, cause I could get any response from you

**Comment by lexaabrahamsen** [comment]
Hey @alexanmtz - Mind if I take a stab at this issue?

**Comment by alexanmtz** [comment]
Hey @lexaabrahamsen, you're now assigned and you can start to work on this issue 👍

**Comment by etfaghaoubeid** [comment]
@alexanmtz I Will work on this

**Comment by etfaghaoubeid** [comment]
@alexanmtz  ??

**Comment by alexanmtz** [comment]
You can start to work on this @etfaghaoubeid 👍

**Comment by etfaghaoubeid** [comment]
@alexanmtz  I need more information about the issue . like we have "A" and we want "B"

**Comment by alexanmtz** [comment]
@etfaghaoubeid, on the screenshot, the text on Tooltip is written in Portuguese, and we need to use our current solution to display the text in different languages (en and br)

**Comment by etfaghaoubeid** [comment]
@alexanmtz url of the screenshot?  e.g: http://localhost:8082/#/tasks/all

**Comment by alexanmtz** [comment]
It's exactly this one @etfaghaoubeid 👍

**Comment by etfaghaoubeid** [comment]
i have made new PR
