### ISSUE TITLE
Add contact author to task page

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#606]
Add a new first item on the task page `Contact author` which will open a dialog to send a message for the user who added an issue on Gitpay.

### Why
We need a way to contact the author to make questions about that issue.

### Level
Beginner

### Screenshot attached
Our current bar where the new button should be placed:
<img width="712" alt="Screen Shot 2020-04-07 at 12 40 44 PM" src="https://user-images.githubusercontent.com/88840/78660233-0a9e5980-78cd-11ea-8b95-f215f1e3c896.png">

The dialog from invite (it should be a dialog with the textarea only):
<img width="453" alt="Screen Shot 2020-04-07 at 12 42 28 PM" src="https://user-images.githubusercontent.com/88840/78660413-4fc28b80-78cd-11ea-8311-e50d89f1f992.png">

### How to reproduce the user scenario
 - Create a user
 - Import an issue
 - Create another user
 - On the task page, the user should be able to contact the author

### Tips
Check our existing invite feature

**Comment by adelmojnr** [comment]
Hi, I'm interested

**Comment by alexanmtz** [comment]
Hello @adelmojnr, you're now assigned and you can start to work on this issue 👍

**Comment by EANimesha** [comment]
I am interested in this. I can really work on this issue. Assign me.

**Comment by alexanmtz** [comment]
@adelmojnr are you still working on this?

**Comment by alexanmtz** [comment]
Hello @EANimesha, you're now assigned and you can start to work on this issue

**Comment by gauraws** [comment]
Hi, I am beginner, can I work on this issue?

**Comment by alexanmtz** [comment]
Hello @gauraws, there's someone already assigned, so you should preferably get another one unassigned if you want to have your code integrated.
