### ISSUE TITLE
Delete account 

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#607]
We should be able to delete a user account completely.

You should do this by adding a new option in our user account menu called _Settings_ and then the on this new settings page, an option Delete my account in red should be available, once the user clicks, a confirm dialog should display a message **Are you sure that you want to delete your account?** should be displayed with a confirm and cancel buttons.

### Why
We should provide an option in our platform to delete accounts, instead of doing this by user request.

### Level
Beginner

### Screenshot attached
<img width="385" alt="Screen Shot 2020-04-07 at 12 53 09 PM" src="https://user-images.githubusercontent.com/88840/78661656-71247700-78cf-11ea-9ccc-e6b97a4c1e2e.png">

### How to reproduce the user scenario
 - Create a user

### Tips
Please reuse our existing Material-UI components to create the buttons and screens.

**Comment by spikeboom** [comment]
I would like to work on this issue.

**Comment by alexanmtz** [comment]
Hello @spikeboom, thanks for your interest. You're now assigned to work on this issue 👍

**Comment by sachin-duhan26** [comment]
I would like to work on this issue.

**Comment by spikeboom** [comment]
@alexanmtz a função para deletar a conta deve excluir também as atividades relacionadas àquele usuário?

**Comment by spikeboom** [comment]
@alexanmtz a função deletar conta permanentemente deve deletar também as tarefas relacionadas àquele usuário?

**Comment by alexanmtz** [comment]
Bem lembrado @spikeboom, vamos deletar as tarefas associadas e interesse em tarefas (`Assigned`), e na mensagem de confirmação notificar isso 👍
