### ISSUE TITLE
Account Takeover Design Bug

### ISSUE THREAD

**Issue by huzaifahere** [worknenjoy/gitpay#617]
Here are steps to take over the account

1.  Your web application has three sign up features.
 Github, BitBucket, Through Email

2. Register the account with my Gmail address (eg: test@gmail.com) using email and password flow. No verification link sent to the email. 
3. Logged out and tried to create an account using the sign up with google using the same Google account used in Step 2 (i.e., test@gmail.com). [victim will do this action]

4. Accounts created in step 2 & 3 got linked, because of the same email address. 

5. Boom! an attacker able to login with the email and password used in step 2

Account created with email and password flow (in step 2) is never verified, due to which attacker can create accounts with victims' email addresses and can take over the account.

**Comment by huzaifahere** [comment]
Step 3: Logged out and tried to create an account using the sign up with Github using the same Google account used in Step 2 (i.e., test@gmail.com). [victim will do this action]
Clarification: Github account is made from Gmail (test@gmail.com)

**Comment by alexanmtz** [comment]
This is part of #524

**Comment by alexanmtz** [comment]
Done
