### ISSUE TITLE
Issue doesn't exists anymore in GitHub but is showing in GitPay task list

### ISSUE THREAD

**Issue by VictorAlessander** [worknenjoy/gitpay#625]
Description 

### Why
Seems like a bug.

### Level
Beginner, I guess.

### Current behavior
Issue was deleted in GitHub, but in GitPay shows a record with title "blah". When the task is opened, nothing is loaded.

### Expected behavior
When issue is deleted from GitHub, in GitPay I guess that needs to disappear.

### Useful links
  - https://github.com/sanjaypokkali/test/issues/1

### Screenshot attached
![image](https://user-images.githubusercontent.com/21283066/79692928-555d9100-823e-11ea-90e8-38c7beb2df06.png)
![image](https://user-images.githubusercontent.com/21283066/79692937-5a224500-823e-11ea-9018-1838d5eefff5.png)

### How to reproduce the user scenario
- Open the task list and enter in the first task (at least for now)

### What you will need to complete this issue
For now I don't know

### Tips
Important things to know to better find the solution for this task

**Comment by alexanmtz** [comment]
Thanks for reporting @VictorAlessander 👍

**Comment by alexanmtz** [comment]
Another commit that runs a script to look for invalid tasks that solve the issue. So the invalid issue was deleted and the user received a confirmation.
