### ISSUE TITLE
TASKS button on the tasks page should take us to the exact task list page from where we opened the task.

### ISSUE THREAD

**Issue by mani-developer** [worknenjoy/gitpay#630]
Description 

### Why

 Better navigation options from a particular task page back to the Task List (Coming back to the exact task list page from where we opened a particular task )

### Current behavior
From the “Task list” page we see the list of tasks. 
![image](https://user-images.githubusercontent.com/63766141/79870652-e8462900-8400-11ea-9570-28a4a52ef549.png)

And we  navigate further to see more tasks by using the < > arrows on the bottom of the page.
![image](https://user-images.githubusercontent.com/63766141/79870679-f4ca8180-8400-11ea-851a-67a060de8d1b.png)

For instance wanted to open a task that’s in 3rd page (21- 30)  - And the below task page in open.
![image](https://user-images.githubusercontent.com/63766141/79870736-0e6bc900-8401-11ea-9f10-efb117a6c702.png)
Then if we wanted to go back to the same page from where we landed at this task (3rd page of “Task List”). there is no <back> option. So we have to use TASK button with up arrow ( which is taking us back to the first page of the task list. (Task 1 to 10). 
![image](https://user-images.githubusercontent.com/63766141/79871011-66a2cb00-8401-11ea-81dc-6a9a8cb8e71f.png)

So if we wanted to continue browsing  the tasks, then we should start from the beginning.

### Expected behavior
The ^TASKS button(shown below) in the task page should take us to the exact previous page instead of the first page of task list.
![image](https://user-images.githubusercontent.com/63766141/79871397-e892f400-8401-11ea-82ad-ac9ccbc3cf16.png)

### How to reproduce the user scenario
-Log in
- Explore tasks
- Navigate to some page by clicking the > arrow on the bottom.
- Open a task by clicking on the title (Task column of the table)
- From the task page click ^ TASKS button on the top
- You should land on the same page from where you opened this taks.

**Comment by EANimesha** [comment]
I am interested in this. Assign me. I started working on this

**Comment by maryamtb** [comment]
Hello, I would like to be assigned to this issue.

**Comment by Shawn-Noruzi** [comment]
@EANimesha  Hi, you're going to need to retain memory of the page section and pass that through the components. 

You can create an increment value for the # of times a user clicks the next page button and save that into the state, recall that value when the component re-renders using the consturctor() life cycle method. 

I haven't looked into component behavior with regards to data flow after you click next page -> click on a task -> click on TASKS button so you'll have to see how the data flow is there to properly pass the state value through. 

This is what I'd do atleast. If you have any questions I'm available here or on our slack page.

**Comment by thenamannanda** [comment]
Can you assign me this issue, I would like to contribute

**Comment by alexanmtz** [comment]
Not relevant anymore, please @sparshy you can work in another issue
