### ISSUE TITLE
Codebase Should support usage of a daily rotating file logging system

### ISSUE THREAD

**Issue by Adekoreday** [worknenjoy/gitpay#638]
Description 

### Why
Logging of details and error on the console makes it difficult to have a detailed history of errors and user interactions with the application on production over a long period of time.

### Level
Beginner

### Current behavior
On start of the application details of interactions are logged via the console, this makes it difficult to know the following

-  level of importance of some logs such as information, error, warning
-  keeping records of transaction history with the application.

### Expected behavior
- A daily rotating file logging system should log information on files, console, and optionally a configuration to enable logging on file or console or both depending on the environment.

- After 24hours each log file should be zipped to keep our application size in check.

### Screenshot attached
<img width="485" alt="Screen Shot 2020-04-27 at 9 52 57 PM" src="https://user-images.githubusercontent.com/44194416/80420714-1e891a00-88d3-11ea-99f8-58f0d3da1d36.png">

### How to reproduce the user scenario
 - start the application and interact with it.

### Tips
leverage of node.js logging libraries

**Comment by navneet79** [comment]
Hi , Can I work on this issue?

**Comment by Adekoreday** [comment]
if @alexanmtz approves.

wrote some stuff on it lately
you can start from this blog post
 https://korey.ml/configuring-daily-rotating-file-logging-system-in-nodejs/

**Comment by alexanmtz** [comment]
that's great @Adekoreday, very good article. So you're interested to work on this? Or you want to share your reference so other contributors can learn from your article?

**Comment by Adekoreday** [comment]
Sharing my reference to make the task easier for @navneet79

**Comment by Adekoreday** [comment]
@navneet79 are you still interested or should I take up the task?

**Comment by Adekoreday** [comment]
@alexanmtz  will like to go ahead and implement this

**Comment by alexanmtz** [comment]
hey @Adekoreday you want to continue to work on this? Do you want to be assigned?

**Comment by Adekoreday** [comment]
i'll continue work on this was waiting on your approval

**Comment by alexanmtz** [comment]
Great @Adekoreday , you're now assigned 👍
