### ISSUE TITLE
After page refresh, task list ignores the label filters selected and shows all tasks

### ISSUE THREAD

**Issue by VictorAlessander** [worknenjoy/gitpay#644]
When a label filter is selected and have a page refresh, the label and the path of page still are the same but the content in task list is referenced to all tasks.

### Why
Causes unexpected behavior.

### Level
Easy/Medium

### Current behavior
After page refresh, the content in task list aren't equal to label filters selected.

### Expected behavior
After page refresh, the content in task list needs to be equals to label filters selected.

### Useful links
xxxxxxx

### Screenshot attached
![image](https://user-images.githubusercontent.com/21283066/80868565-e20e4300-8c71-11ea-8e79-81113ad21158.png)

### How to reproduce the user scenario
 - Open "Explore Tasks"
- See that the content in task list are equals to 'all'.
- Select any label filter and see the changes in task list;
- Now refresh the page and see that the content in task list are equals to 'all'

### What you will need to complete this issue
Understanding of React/Redux;

### Tips
Understand the functionality of task list flow.

**Comment by ampsteric** [comment]
can i work on this issue as a first time contributor??

**Comment by alexanmtz** [comment]
Yes @ampsteric, you can start to work on this to do your first contribution 👍

**Comment by ampsteric** [comment]
the Backend has a error named:
TypeError: OAuth2Strategy requires a clientID option
#2544

**Comment by alexanmtz** [comment]
@ampsteric you need to follow this step in our documentation:

### Env to do some actions
For a full integration with api services used by the platform, you will need the api keys. You should make a copy of your .env.example to .env with the right credentials.

You can do this with: `cp .env.example .env`

**Comment by alexanmtz** [comment]
The filter was removed so this can be closed
