### ISSUE TITLE
Task opening crash

### ISSUE THREAD

**Issue by AlekseiKorolev** [worknenjoy/gitpay#648]
Description 

### Why
Throws an error

### Level
Entry

### Current behavior
The profile page, tasks list (https://gitpay.me/#/profile/tasks)
Click on any task (task column) throws an error

### Expected behavior
Open description of the selected task

### Useful links
https://www.loom.com/share/8f1e2fcf99bb4d54b4f87f1b6e623740

### Screenshot attached
![image](https://user-images.githubusercontent.com/42728999/81184182-67666000-8fb0-11ea-8278-3fff4fa70b65.png)

### How to reproduce the user scenario
Go to https://gitpay.me/#/profile/tasks and click on the task

### What you will need to complete this issue
No need

### Tips
No need

**Comment by alexanmtz** [comment]
Thanks @AlekseiKorolev, I fixed this for now with this commit:
https://github.com/worknenjoy/gitpay/commit/1ec474e8b93a7f55e547e4ef55712508b078c6d8

We need to better handle empty values maybe we will make the name of the user required when register.

Thanks for reporting this 👍
