### ISSUE TITLE
Chip filter with wrong style on click

### ISSUE THREAD

**Issue by mathvaleriano** [worknenjoy/gitpay#653]
Change the button style when it has been clicked

### Why
Improve the experience

### Level
Beginner

### Current behavior
When I click on MuiChip filter button in task list the style has been updated by focus... so to see the real checked style I need to click outside of the button.

### Expected behavior
When I click on MuiChip filter button, it should have the selected style

### Useful links
https://gitpay.me/#/tasks/open

### Screenshot attached
![image](https://user-images.githubusercontent.com/12265496/82105360-4eb52300-96f1-11ea-80eb-6d2b1ebc5eb3.png)
![image](https://user-images.githubusercontent.com/12265496/82105368-570d5e00-96f1-11ea-9a86-951db2b09527.png)

### How to reproduce the user scenario
1. access https://gitpay.me/#/tasks/open
2. click on another MuiChip button like "All"
3. the button will not be green

**Comment by sep2001aryan** [comment]
Hello I would like to work on this issue :)

**Comment by alexanmtz** [comment]
Hello @sep2001aryan, that's great, you're now assigned 👍

**Comment by sep2001aryan** [comment]
On it 😁

**Comment by Simran-Chaudhary** [comment]
Hey is this fixed? If not I'd like to work on it.

**Comment by Simran-Chaudhary** [comment]
Saw it wasn't fixed yet, so raised a pr. 
https://github.com/worknenjoy/gitpay/pull/710
