### ISSUE TITLE
Fix translation of the button text

### ISSUE THREAD

**Issue by mathvaleriano** [worknenjoy/gitpay#654]
### Why
To use correct text when the site has been using pt-br

### Level
Beginner

### Current behavior
Wrong text on button "make an offer"

### Expected behavior
It should be "Faça uma proposta"

### Useful links
  https://gitpay.me/#/task/339

### Screenshot attached
![image](https://user-images.githubusercontent.com/12265496/82105638-b91a9300-96f2-11ea-99d7-57e92652753e.png)

### How to reproduce the user scenario
Just access the link and scroll down to see the button on the right side

**Comment by MTLChrisLEE** [comment]
Shouldn't it be "Fazer uma oferta" instead of "Faça uma proposta" ?

**Comment by alexanmtz** [comment]
@MTLChrisLEE and @mathvaleriano we need to fix the button layout break, and the text should be proposed here: https://crowdin.com/project/gitpay/pt-BR#

Just send the corrections for Portuguese and feel free to help with the translation.

**Comment by MTLChrisLEE** [comment]
@alexanmtz  
There is a property string in br.json file (frontend/src/translation/result) with the field 
"task.interested.offer" and it says "Fazer uma oferta"

https://github.com/MTLChrisLEE/gitpay/commit/14d8c8ece7b335b9efc6d58a3ffdbc74f7034c39

As you my see on my forked repo, I created a branch and fixed the issue(I just changed the id value of FormattedMessage on the line 745). However, I am struggling to fix some code conventions. I tried npm run lint-fix but it's doing nothing :(

**Comment by alexanmtz** [comment]
Great @MTLChrisLEE, yeah, there are other nonrelated changes, and it seems your code is outdated, and maybe if you do your change from a fresh branch and create the PR?

**Comment by alexanmtz** [comment]
Fixed 
![Screen Shot 2020-10-30 at 8 44 55 PM](https://user-images.githubusercontent.com/88840/97750310-d2709980-1af0-11eb-8fa0-cd698445c196.png)
