### ISSUE TITLE
Better check for active account

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#70]
Some accounts are activated without bank accounts, so we need a better handle to make sure that a account is active only if have a successful bank account registered

**Comment by alexanmtz** [comment]
Please check @mthais if after this merge your account is working better 🚶

**Comment by mthais** [comment]
@alexanmtz it's not working correct yet. When I insert some bank data and click on the button "Próximo passo", the system don't show me some validation message, but I have access in the next step and my account don't stay  activated. Check it, please!

**Comment by alexanmtz** [comment]
We've made a lot of improvements and bug fixes to better handle the account activation 🚀
