### ISSUE TITLE
How to add labels?

### ISSUE THREAD

**Issue by drzraf** [worknenjoy/gitpay#744]
How are labels working

### Why
Don't understand the UI

### Level
Level required to conclude this issue

### Current behavior
Label buttons not present. No where to click or fill text. No explanations.

### Expected behavior
I should be able to add labels

### Screenshot attached
![Screenshot from 2020-11-27 12-04-21](https://user-images.githubusercontent.com/1169926/100462220-b4269b00-30a8-11eb-9e5a-db3b82052683.png)

### How to reproduce the user scenario
 - Look at the right on an opened task.

**Comment by alexanmtz** [comment]
@drzraf Thanks for open this issue. The labels came from the labels set on the Github original issue. But we should be clear, so we will change the text to make it clear. Thanks for your feedback!

**Comment by alexanmtz** [comment]
@drzraf, you can contribute with the text strings on:
https://crowdin.com/project/gitpay
