### ISSUE TITLE
New login page

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#839]
We will have a new login page, and you should create a new route on the front-end for the login process, replacing this one:
https://gitpay.me/#/login

This will replace our sign-in / sign-up process.

### Why
This is the beginning of our new redesign, so we will offer a better experience for our user onboarding. We need to add our terms of service when creating an account.

### Level
Medium

### Useful links
  - Material-UI: https://material-ui.com/

### Screenshot attached
![00 01_Login_signup](https://user-images.githubusercontent.com/88840/124454748-1a834280-dd89-11eb-88e4-cff13488cb17.jpg)
![00 00_Login](https://user-images.githubusercontent.com/88840/124454739-1820e880-dd89-11eb-8a83-e374a2ac16d7.jpg)
![00 02_Login_termos](https://user-images.githubusercontent.com/88840/124454753-1bb46f80-dd89-11eb-8fdd-6ee2b613de3e.jpg)

### How to reproduce the user scenario
- Scenario 1
   - Run the project locally
   - Go to login `/#/login` route

### What you will need to complete this issue
- We need to provide the development test keys for login into different services not supported now, like Gmail and Facebook.

### Tips
- All the UI will use Material UI (https://material-ui.com/)
- Use our translation library Run `npm run translate` on the `/frontend` folder to sync translation before sending the PR

**Comment by Sockalingam29** [comment]
Can you send the background image?

**Comment by alexanmtz** [comment]
Here is the background image @Sockalingam29, let me know if you have any questions in how to proceed 👍 

![cover](https://user-images.githubusercontent.com/88840/130669148-6f7e4471-7f0b-437f-8620-efc7d7bd5b19.jpeg)

**Comment by Sockalingam29** [comment]
Thanks 👍

**Comment by alexanmtz** [comment]
solved by #973
