### ISSUE TITLE
Run project on Linux machine

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#842]
We're having issues with authentication on Linux machines. We should be able to run the server and the docker on Linux

### Why
Most of our developers are trying to run on Linux and they're having issues

### Level
Beginner

### Current behavior
The project already work on Linux with no issues, but when we try to create an account, we have an issue with the redirect with token

### Expected behavior
The project should run and create accounts with login working properly on Linux environments

### How to reproduce the user scenario
- Scenario 1
   - Run the project locally
   - Create a user

### What you will need to complete this issue
- You need a Linux environment
- You need to debug in our authentication methods to figure out what's the issue, so we can find a solution

### Tips
- All the UI will use Material UI (https://material-ui.com/)
- Use our translation library Run `npm run translate` on the `/frontend` folder to sync translation before sending the PR

**Comment by MikeyJL** [comment]
I can take a look at this. My system is running Ubuntu 20.04.

**Comment by alexanmtz** [comment]
Hey, @MikeyJL we have an open pull request #844 from @adelmojnr, you want to maybe check out his branch and test?

Or you can suggest a solution and we can work together on this.

I think he sent a practical solution, but maybe we can improve it to have a better way to run on Linux without an extra file as he suggested. Please take a look and let me know what do you think

**Comment by MikeyJL** [comment]
Sure, looked at it already and it's good. I personally can't think of anything else but will drop it here if anything comes to mind.
