### ISSUE TITLE
Can't  add bank account

### ISSUE THREAD

**Issue by Artturin** [worknenjoy/gitpay#850]
### Current behavior
Can't add my bank account therefore i cannot receive the bounty for https://gitpay.me/#/task/524

"Send the solution" doesn't work either

i added my paypal account but i do not know if that is enough

### Screenshot attached
![image](https://user-images.githubusercontent.com/56650223/128601333-dba4cca6-8b0f-4ed1-a1d1-8d902e9dffa9.png)

![image](https://user-images.githubusercontent.com/56650223/128601426-9d94efd9-9037-4f0d-b436-99e723ba73c9.png)

**Comment by alexanmtz** [comment]
Hello @Artturin, thanks for reporting this; I found that Stripe, the payment platform we use to make the payments, had deprecated a capability recently, so that's why it was an error to create your account.

I just merged #851, and it's already deployed, so can you try again and let me know if it works?

**Comment by Artturin** [comment]
It works now, however 

i dont know what id number you're asking and there's no country field 

![image](https://user-images.githubusercontent.com/56650223/128604694-e30e648d-741d-4991-97ed-affce8107fb4.png)

Is it enough to provide an IBAN in the Account number field? i also have a SWIFT/BIC if needed
![image](https://user-images.githubusercontent.com/56650223/128604700-fb294e33-fa34-4a63-ad35-05c30d632f4a.png)

**Comment by alexanmtz** [comment]
Hello @Artturin thanks for your feedback 👍 

In your case, in Finland, the number is the _Personal identity code (HETU)_

For your bank, please provide your IBAN in both fields.

**Comment by Artturin** [comment]
according to https://stripe.com/docs/connect/required-verification-information#FI-full-individual--card_payments|transfers

you don't need to collect `individual.personal_id_number`
Neither do you need to collect website for individuals


Also, there is no Email or phone number field 
![screenshot_2021-08-07_18-07-00_075730430](https://user-images.githubusercontent.com/56650223/128605897-4f9feaaa-06fe-4ead-b6c9-db365aa48763.png)

**Comment by Artturin** [comment]
Solved via email
