### ISSUE TITLE
Stripe new required fields to update account

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#852]
Update our account activation fields to fit based on country requirements.

As in this Stripe reference: 
https://stripe.com/docs/connect/required-verification-information#BR-full-individual--card_payments|transfers 

We will need to generate the form based on the requirements.

For all countries, now the phone number is required, so it should be added.

In the bank step, we should check the required fields, cause sometimes it requires `routing_number` and `account_number` and in other situations, it may require the IBAN, so our form should adjust to that.

### Why
We need to activate our account based on user requirements.

### Level
Medium

### Current behavior
Most of the accounts work on Gitpay, but in some situations, the form is not the right one for that country

### Expected behavior
Make the account activation list the required field based on Stripe requirements.

### Useful links
  - Github API: https://docs.github.com/en/rest
  - Material-UI: https://material-ui.com/
  - Stripe Documentation: https://stripe.com/docs/connect/required-verification-information#BR-full-individual--card_payments|transfers

### Screenshot attached
![pageshot of 'Gitpay - Bounties for git issues solved' @ 2021-08-07-1951'16](https://user-images.githubusercontent.com/88840/128609532-e8c0b92e-8764-4062-8e65-3513d7a906ef.png)
In this example in https://gitpay.me/#/profile/payment-options, my account is pending because I did not update the website (there's an input for that already), phone number should be added, the email should set the user registration e-mail, and in this case for Brazil, the document is not mandatory, so my account should not list as pending requirements to complete the account verification.

### How to reproduce the user scenario
- Scenario 1
   - Run the project locally
   - Create a user
   - Go to Setup Bank account - https://gitpay.me/#/profile/payment-options
   - Activate your account

### What you will need to complete this issue
You will need Stripe keys to complete this issue.

### Tips
- All the UI will use Material UI (https://material-ui.com/)
- Use our translation library Run `npm run translate` on the `/frontend` folder to sync translation before sending the PR

**Comment by Artturin** [comment]
This is important/critical for eu since IBAN is used here

**Comment by smrutiparida** [comment]
Hi. I am interested to take up the work. Is this still open for bounty ? Before doing that, I wanted to check on how the bounty works ? What is the bounty amount, how shall you pay for the same and how to ensure that payment shall happen once work is completed .

**Comment by alexanmtz** [comment]
@smrutiparida you can make an offer for the bounty amount, here's the link:
https://gitpay.me/#/task/619

Once the work is completed, you can request the payment when the PR is merged, and the platform will check the status and send the money

Once I accept your offer I can pay and the payment is on Gitpay to be transferred to you.

Let me know if you have any question
