### ISSUE TITLE
GitpayBot is not posting issues on creation when a payment is made

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#871]
The GitpayBot is not commenting on the issue when we create and make a payment of a bounty for an issue. 

Investigate the cause and a find solution to new issues created and a script to sync existing posts.

Our current way to do it is by using a Bot user, and our account was flagged.

Look for another way of doing it.

You will need to create a flag on the model like `synced: true` on the task to mark the one sync, to the existing ones, or you're welcome to have a new solution.

### Expected behavior
When an issue is added or a new payment is made to a given issue, it should post with our GitpayBot.

### Useful links
  - Github API: https://docs.github.com/en/rest

**Comment by VictorAlessander** [comment]
Hey, could you assign this issue to me?

**Comment by alexanmtz** [comment]
Changing the Bot account seems to work for now so we will close
