### ISSUE TITLE
change username

### ISSUE THREAD

**Issue by nerd36** [worknenjoy/gitpay#872]
Description 

### Why
Removing my real name

### Expected behavior
Allow changing username
https://gitpay.me/#/organizations/105/projects/176

### Tips
- Github itself allow it

**Comment by alexanmtz** [comment]
Hey @nerd36 , now you can change your name in your account settings: https://gitpay.me/#/profile/user-account

I can close this one now, it was solved on #987

**Comment by alexanmtz** [comment]
Hey @nerd36 , now you can change your name in your account settings: https://gitpay.me/#/profile/user-account

I can close this one now, it was solved on #987
