### ISSUE TITLE
Change country

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/gitpay#934]
The change country dropdown in the top bar is not working anymore, please check the cause of this issue.

**Comment by vczb** [comment]
Hello :wave: 

Can I take a shot on this?

**Comment by alexanmtz** [comment]
Hey @vczb, good to see you again :-)

I just updated the platform to use new react and new node versions, and some bugs came from it, like this one, so you're good to go to fix it on master 👍

**Comment by vczb** [comment]
cool @alexanmtz I'm happy to be back :fire:

**Comment by alexanmtz** [comment]
@vczb The language dropdown is in https://gitpay.me/#/profile/settings for now

**Comment by alexanmtz** [comment]
The component seems to work now @vczb, check in production

**Comment by vczb** [comment]
> The component seems to work now @vczb, check in production

yeah @alexanmtz just checked and looks fine!
